### PR TITLE
Ingest: Exit if child process redirect io failed

### LINKED ISSUE #1695: Ingest重复调用导致系统资源被耗尽的问题
**描述(Description)**
操作系统 centos 7 64位

从绝对路径启动srs去拉流并推动到SRS（只要不在srs的目录下），会出现大量srs进程，导致系统资源消耗光。例如/usr/local/src/srs/trunk/objs/srs -c  /usr/local/src/srs/trunk/conf/ingest.conf 
用./objs/srs -c conf/ingest.conf启动就不会出现问题。
从日志看是没有创建ffmpeg-ingest-XXX.log权限导致，
产生的第一个srs进程的父进程id是1，srs进程也无法用kill结束，只能重启服务器

1. SRS版本(Version): `3.0.140`
1. SRS的日志如下(Log):
```
[2020-04-08 20:32:19.705][Trace][1701][0] srs checking config...
[2020-04-08 20:32:19.705][Trace][1701][0] ips, iface[0] eth0 ipv4 0x11043 192.168.6.81
[2020-04-08 20:32:19.705][Trace][1701][0] devices, intranet eth0 192.168.6.81
[2020-04-08 20:32:19.705][Warn][1701][0][0] stats network use index=0, ip=192.168.6.81
[2020-04-08 20:32:19.705][Warn][1701][0][0] stats disk not configed, disk iops disabled.
[2020-04-08 20:32:19.705][Trace][1701][0] write log to console
[2020-04-08 20:32:19.705][Trace][1701][0] features, rch:on, dash:on, hls:on, hds:on, hc:on, ha:on, hs:on, hp:on, dvr:on, trans:on, inge:on, stat:on, sc:on
[2020-04-08 20:32:19.705][Trace][1701][0] SRS on  amd64 x86_64, conf:/usr/local/src/srs/trunk/conf/jjlive.slave.conf, limit:1000, writev:1024, encoding:little-endian, HZ:100
[2020-04-08 20:32:19.705][Trace][1701][0] mw sleep:350ms. mr enabled:on, default:0, sleep:350ms
[2020-04-08 20:32:19.705][Trace][1701][0] gc:on, pq:30000ms, cscc:[0,16), csa:on, tn:on(may hurts performance), ss:auto(guess by merged write)
[2020-04-08 20:32:19.705][Trace][1701][0] system default latency(ms): mw(0-350) + mr(0-350) + play-queue(0-30000)
[2020-04-08 20:32:19.705][Warn][1701][0][0] SRS/3.0.140 is beta
[2020-04-08 20:32:19.705][Trace][1701][0] http: root mount to ./objs/nginx/html
[2020-04-08 20:32:19.706][Trace][1701][0] st_init success, use epoll
[2020-04-08 20:32:19.706][Trace][1701][700] server main cid=700, pid=1701, ppid=1636, asprocess=0
[2020-04-08 20:32:19.706][Trace][1701][700] write pid=1701 to /usr/local/src/srs/trunk/objs/srs.pid success!
[2020-04-08 20:32:19.707][Trace][1701][700] RTMP listen at tcp://0.0.0.0:1935, fd=7
[2020-04-08 20:32:19.707][Trace][1701][700] signal installed, reload=1, reopen=10, fast_quit=15, grace_quit=3
[2020-04-08 20:32:19.707][Trace][1701][700] http: api mount /console to ./objs/nginx/html/console
[2020-04-08 20:32:19.709][Trace][1701][700] parse success, ingest=livestream, vhost=__defaultVhost__
[2020-04-08 20:32:19.709][Warn][1706][700][2] Ingester: Ignore error, code=3030 : ingester start : redirect output : open process 1 ./objs/ffmpeg-ingest-__defaultVhost__-live-livestream.log failed
thread [1706][700]: do_cycle() [src/app/srs_app_ingest.cpp:246][errno=2]
thread [1706][700]: start() [src/app/srs_app_process.cpp:204][errno=2]
thread [1706][700]: srs_redirect_output() [src/app/srs_app_process.cpp:159][errno=2]
[2020-04-08 20:32:19.719][Trace][1701][700] fored process, pid=1706, bin=/usr/local/src/srs/trunk/objs/ffmpeg/bin/ffmpeg, stdout=./objs/ffmpeg-ingest-__defaultVhost__-live-livestream.log, stderr=./objs/ffmpeg-ingest-__defaultVhost__-live-livestream.log, argv=/usr/local/src/srs/trunk/objs/ffmpeg/bin/ffmpeg -loglevel info -i rtsp://192.168.97.26/ch01 -vcodec copy -acodec copy -f flv -y rtmp://127.0.0.1:1935/live?vhost=__defaultVhost__/livestream
[2020-04-08 20:32:22.706][Warn][1707][700][2] Ingester: Ignore error, code=3030 : ingester start : redirect output : open process 1 ./objs/ffmpeg-ingest-__defaultVhost__-live-livestream.log failed
thread [1707][700]: do_cycle() [src/app/srs_app_ingest.cpp:246][errno=2]
thread [1707][700]: start() [src/app/srs_app_process.cpp:204][errno=2]
thread [1707][700]: srs_redirect_output() [src/app/srs_app_process.cpp:159][errno=2]
[2020-04-08 20:32:22.716][Trace][1706][700] fored process, pid=1707, bin=/usr/local/src/srs/trunk/objs/ffmpeg/bin/ffmpeg, stdout=./objs/ffmpeg-ingest-__defaultVhost__-live-livestream.log, stderr=./objs/ffmpeg-ingest-__defaultVhost__-live-livestream.log, argv=/usr/local/src/srs/trunk/objs/ffmpeg/bin/ffmpeg -loglevel info -i rtsp://192.168.97.26/ch01 -vcodec copy -acodec copy -f flv -y rtmp://127.0.0.1:1935/live?vhost=__defaultVhost__/livestream
[2020-04-08 20:32:23.673][Trace][1706][704] RTMP client ip=192.168.6.91, fd=8
[2020-04-08 20:32:23.673][Warn][1706][704][104] client disconnect peer. ret=1008
[2020-04-08 20:32:25.707][Warn][1708][700][2] Ingester: Ignore error, code=3030 : ingester start : redirect output : open process 1 ./objs/ffmpeg-ingest-__defaultVhost__-live-livestream.log failed
thread [1708][700]: do_cycle() [src/app/srs_app_ingest.cpp:246][errno=2]
thread [1708][700]: start() [src/app/srs_app_process.cpp:204][errno=2]
thread [1708][700]: srs_redirect_output() [src/app/srs_app_process.cpp:159][errno=2]
[2020-04-08 20:32:25.716][Trace][1707][700] fored process, pid=1708, bin=/usr/local/src/srs/trunk/objs/ffmpeg/bin/ffmpeg, stdout=./objs/ffmpeg-ingest-__defaultVhost__-live-livestream.log, stderr=./objs/ffmpeg-ingest-__defaultVhost__-live-livestream.log, argv=/usr/local/src/srs/trunk/objs/ffmpeg/bin/ffmpeg -loglevel info -i rtsp://192.168.97.26/ch01 -vcodec copy -acodec copy -f flv -y rtmp://127.0.0.1:1935/live?vhost=__defaultVhost__/livestream
[2020-04-08 20:32:28.708][Warn][1709][700][2] Ingester: Ignore error, code=3030 : ingester start : redirect output : open process 1 ./objs/ffmpeg-ingest-__defaultVhost__-live-livestream.log failed
thread [1709][700]: do_cycle() [src/app/srs_app_ingest.cpp:246][errno=2]
thread [1709][700]: start() [src/app/srs_app_process.cpp:204][errno=2]
thread [1709][700]: srs_redirect_output() [src/app/srs_app_process.cpp:159][errno=2]
[2020-04-08 20:32:28.717][Trace][1708][700] fored process, pid=1709, bin=/usr/local/src/srs/trunk/objs/ffmpeg/bin/ffmpeg, stdout=./objs/ffmpeg-ingest-__defaultVhost__-live-livestream.log, stderr=./objs/ffmpeg-ingest-__defaultVhost__-live-livestream.log, argv=/usr/local/src/srs/trunk/objs/ffmpeg/bin/ffmpeg -loglevel info -i rtsp://192.168.97.26/ch01 -vcodec copy -acodec copy -f flv -y rtmp://127.0.0.1:1935/live?vhost=__defaultVhost__/livestream
[2020-04-08 20:32:31.708][Warn][1710][700][2] Ingester: Ignore error, code=3030 : ingester start : redirect output : open process 1 ./objs/ffmpeg-ingest-__defaultVhost__-live-livestream.log failed
thread [1710][700]: do_cycle() [src/app/srs_app_ingest.cpp:246][errno=2]
thread [1710][700]: start() [src/app/srs_app_process.cpp:204][errno=2]
thread [1710][700]: srs_redirect_output() [src/app/srs_app_process.cpp:159][errno=2]
[2020-04-08 20:32:31.716][Trace][1707][700] -> IGS time=11014ms, ingesters=1, #0(alive=11014ms, __defaultVhost__/livestream)
[2020-04-08 20:32:31.716][Trace][1706][700] -> IGS time=11015ms, ingesters=1, #0(alive=11015ms, __defaultVhost__/livestream)
[2020-04-08 20:32:31.718][Trace][1708][700] -> IGS time=11016ms, ingesters=1, #0(alive=11016ms, __defaultVhost__/livestream)
[2020-04-08 20:32:31.718][Trace][1709][700] fored process, pid=1710, bin=/usr/local/src/srs/trunk/objs/ffmpeg/bin/ffmpeg, stdout=./objs/ffmpeg-ingest-__defaultVhost__-live-livestream.log, stderr=./objs/ffmpeg-ingest-__defaultVhost__-live-livestream.log, argv=/usr/local/src/srs/trunk/objs/ffmpeg/bin/ffmpeg -loglevel info -i rtsp://192.168.97.26/ch01 -vcodec copy -acodec copy -f flv -y rtmp://127.0.0.1:1935/live?vhost=__defaultVhost__/livestream
[2020-04-08 20:32:31.718][Trace][1709][700] -> IGS time=11017ms, ingesters=1, #0(alive=11017ms, __defaultVhost__/livestream)
[2020-04-08 20:32:31.720][Trace][1701][700] -> IGS time=11014ms, ingesters=1, #0(alive=11014ms, __defaultVhost__/livestream)
[2020-04-08 20:32:34.708][Warn][1745][700][2] Ingester: Ignore error, code=3030 : ingester start : redirect output : open process 1 ./objs/ffmpeg-ingest-__defaultVhost__-live-livestream.log failed
thread [1745][700]: do_cycle() [src/app/srs_app_ingest.cpp:246][errno=2]
thread [1745][700]: start() [src/app/srs_app_process.cpp:204][errno=2]
thread [1745][700]: srs_redirect_output() [src/app/srs_app_process.cpp:159][errno=2]
[2020-04-08 20:32:34.718][Trace][1710][700] fored process, pid=1745, bin=/usr/local/src/srs/trunk/objs/ffmpeg/bin/ffmpeg, stdout=./objs/ffmpeg-ingest-__defaultVhost__-live-livestream.log, stderr=./objs/ffmpeg-ingest-__defaultVhost__-live-livestream.log, argv=/usr/local/src/srs/trunk/objs/ffmpeg/bin/ffmpeg -loglevel info -i rtsp://192.168.97.26/ch01 -vcodec copy -acodec copy -f flv -y rtmp://127.0.0.1:1935/live?vhost=__defaultVhost__/livestream
[2020-04-08 20:32:34.718][Trace][1710][700] -> IGS time=14020ms, ingesters=1, #0(alive=14020ms, __defaultVhost__/livestream)
[2020-04-08 20:32:37.709][Warn][1746][700][2] Ingester: Ignore error, code=3030 : ingester start : redirect output : open process 1 ./objs/ffmpeg-ingest-__defaultVhost__-live-livestream.log failed
thread [1746][700]: do_cycle() [src/app/srs_app_ingest.cpp:246][errno=2]
thread [1746][700]: start() [src/app/srs_app_process.cpp:204][errno=2]
thread [1746][700]: srs_redirect_output() [src/app/srs_app_process.cpp:159][errno=2]
[2020-04-08 20:32:37.718][Trace][1745][700] fored process, pid=1746, bin=/usr/local/src/srs/trunk/objs/ffmpeg/bin/ffmpeg, stdout=./objs/ffmpeg-ingest-__defaultVhost__-live-livestream.log, stderr=./objs/ffmpeg-ingest-__defaultVhost__-live-livestream.log, argv=/usr/local/src/srs/trunk/objs/ffmpeg/bin/ffmpeg -loglevel info -i rtsp://192.168.97.26/ch01 -vcodec copy -acodec copy -f flv -y rtmp://127.0.0.1:1935/live?vhost=__defaultVhost__/livestream
[2020-04-08 20:32:37.719][Trace][1745][700] -> IGS time=17022ms, ingesters=1, #0(alive=17022ms, __defaultVhost__/livestream)
```
1. SRS的配置如下(Config):
```
listen              1935;
max_connections     1000;
pid                 /usr/local/src/srs/trunk/objs/srs.pid;
daemon              off;
srs_log_tank        console;
vhost __defaultVhost__ {
    ingest livestream {
        enabled      on;
        input {
            type    stream;
            url     rtsp://192.168.97.26/ch01;
        }
        ffmpeg      /usr/local/src/srs/trunk/objs/ffmpeg/bin/ffmpeg;
        engine {
            enabled         on;
            perfile {
                re;
                rtsp_transport tcp;
            }
            output          rtmp://127.0.0.1:[port]/live?vhost=[vhost]/livestream;
        }
    }
```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. 不用./objs/srs -c conf/ingest.conf命令启动，在其他目录下用绝对路径的方式启动就会出现

**如何避免**

在配置文件中增加ffmpeg的log文件的存放绝对路径的配置项
ff_log_dir          /usr/local/src/srs/trunk/objs;

### PR DESCRIPTION
**Pull request by rise-worlds**
Fix #1695 
srs进程fork后，因为输出重定向写错误而返回，导致fork的子进程未能退出，从而导致系统资源耗尽。

### CODE REVIEW

File: trunk/src/app/srs_app_process.cpp [hunk 1]
```diff
@@ -212,6 +213,12 @@ srs_error_t SrsProcess::start()
             fprintf(stdout, "process actual cli: %s\n", actual_cli.c_str());
         }
         
+        // output error to stdout and exit child process.
+        if (child_err != srs_success) {
+            fprintf(stdout, "child process error, %s\n", srs_error_desc(child_err).c_str());
+            exit(-1);
```
Comment (winlinvip) [inline trunk/src/app/srs_app_process.cpp]: You can change `srs_redirect_output` to a function call, for example:

```
srs_error_t SrsProcess::redirect_io()
```

This way, when calling, there is no need to define names like `child_err`, but instead:

```
        err = redirect_io();

        if (true) {
            fprintf(stdout, "\n");
            fprintf(stdout, "process ppid=%d, cid=%s, pid=%d, in=%d, out=%d, err=%d\n",
                ppid, cid.c_str(), getpid(), STDIN_FILENO, STDOUT_FILENO, STDERR_FILENO);
            fprintf(stdout, "process binary=%s, cli: %s\n", bin.c_str(), cli.c_str());
            fprintf(stdout, "process actual cli: %s\n", actual_cli.c_str());
        }

        // output error to stdout and exit child process.
        if (err != srs_success) {
            fprintf(stdout, "child process error, %s\n", srs_error_desc(err).c_str());
            exit(-1);
        }
```

Similarly, when implementing, there is no need to define special error variable names, but instead use `err`:

```
srs_error_t SrsProcess::redirect_io()
{
    srs_error_t err = srs_success;

    // for the stdout, ignore when not specified.
    // redirect stdout to file if possible.
    if ((err = srs_redirect_output(stdout_file, STDOUT_FILENO)) != srs_success) {
        return srs_error_wrap(err, "redirect output");
    }

    .......

    return err;
}
```

The variable name `err` is easier to understand and less prone to misuse, making it easier to maintain.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Additional sentence: There is no problem logically, it's great, thank you very much for submitting the PR 😁
Make sure to maintain the markdown structure.

`TRANS_BY_GPT3`

File: trunk/src/app/srs_app_process.cpp (hunk 1 above)
Comment (rise-worlds) [reply trunk/src/app/srs_app_process.cpp]: Already fixed, adding a variable indeed has no practical meaning haha :blush:

`TRANS_BY_GPT3`

File: trunk/src/app/srs_app_process.cpp [hunk 2]
```diff
@@ -212,6 +219,12 @@ srs_error_t SrsProcess::start()
             fprintf(stdout, "process actual cli: %s\n", actual_cli.c_str());
         }
         
+        // output error to stdout and exit child process.
+        if ((err = redirect_io()) != srs_success) {
```
Comment (winlinvip) [inline trunk/src/app/srs_app_process.cpp]: Redirect_io must be done before printing, and after that, it will be printed to the console. This may result in the loss of logs.

```
err = redirect_io();

fprintf(xxx);

if (err != srs_success) {
```

`TRANS_BY_GPT3`

Comment (rise-worlds) [reply trunk/src/app/srs_app_process.cpp]: Already modified, overlooked :sweat:

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Nice 👍

**Review by winlinvip — APPROVED** [review]
