### PR TITLE
GB: Support H.265 for GB28181

### LINKED ISSUE #3407: HEVC: Error empty SPS/PPS when coverting RTMP to HEVC.
1. SRS Version: XCORE-SRS/6.0.23(Bee)

2. SRS Log:

```
[2023-02-09 12:14:02.230][ERROR][27919][4u14n5rj][4] serve error code=5011(RtcRtpMuxer)(Failed to mux RTP packet for RTC) : service cycle : rtmp: stream service : rtmp: receive thread : handle publish message : rtmp: consume message : rtmp: consume video : bridge consume video : package stap-a : sps/pps empty
thread [27919][4u14n5rj]: do_cycle() [./src/app/srs_app_rtmp_conn.cpp:262][errno=4]
thread [27919][4u14n5rj]: service_cycle() [./src/app/srs_app_rtmp_conn.cpp:456][errno=4]
thread [27919][4u14n5rj]: do_publishing() [./src/app/srs_app_rtmp_conn.cpp:1024][errno=11]
thread [27919][4u14n5rj]: consume() [./src/app/srs_app_recv_thread.cpp:380][errno=11]
thread [27919][4u14n5rj]: handle_publish_message() [./src/app/srs_app_rtmp_conn.cpp:1161][errno=11]
thread [27919][4u14n5rj]: process_publish_message() [./src/app/srs_app_rtmp_conn.cpp:1189][errno=11]
thread [27919][4u14n5rj]: on_video_imp() [./src/app/srs_app_source.cpp:2468][errno=11]
thread [27919][4u14n5rj]: on_video() [./src/app/srs_app_rtc_source.cpp:1006][errno=11]
thread [27919][4u14n5rj]: package_stap_a() [./src/app/srs_app_rtc_source.cpp:1093][errno=11](Interrupted system call)
```

3. SRS Config:

```
vhost __defaultVhost__ {
    rtc {
        enabled on;
        rtmp_to_rtc on;
        rtc_to_rtmp on;
    }
    http_remux {
        enabled on;
        mount [vhost]/[app]/[stream].flv;
    }
    hls {
        enabled on;
    }
	dvr {
        enabled      off;
        dvr_path     ./objs/nginx/html/[app]/[stream].[timestamp].mp4;
        dvr_plan     session;
    }
}
```

## Replay

Client pushes RTMP (H265) to SRS service.
`
rtc {
        enabled on;
`rtmp_to_rtc` is set to `on`; it will cause an error, but when set to `off`, it works normally.
        rtc_to_rtmp on;
    }
`

`TRANS_BY_GPT3`

### PR DESCRIPTION
**Pull request by duiniuluantanqin**

### CODE REVIEW

File: trunk/src/app/srs_app_gb28181.cpp [hunk 1]
```diff
@@ -1554,6 +1555,12 @@ SrsGbMuxer::SrsGbMuxer(SrsLazyGbSession* session)
     h264_pps_changed_ = false;
     h264_sps_pps_sent_ = false;
 
+#ifdef SRS_H265
+    hevc_ = new SrsRawHEVCStream();
+    h265_sps_pps_sent_ = false;
```
Comment (chundonglinlin) [inline trunk/src/app/srs_app_gb28181.cpp]: Under the naming convention, change it to `vps_sps_pps_sent_`

`TRANS_BY_GPT3`

File: trunk/src/app/srs_app_gb28181.cpp [hunk 2]
```diff
@@ -1764,6 +1798,182 @@ srs_error_t SrsGbMuxer::write_h264_ipb_frame(char* frame, int frame_size, uint32
...
+
+    // send each frame.
+    while (!avs->empty()) {
+        char* frame = NULL;
+        int frame_size = 0;
+        if ((err = hevc_->annexb_demux(avs, &frame, &frame_size)) != srs_success) {
+            return srs_error_wrap(err, "demux hevc annexb");
+        }
+
+        // 6bits, 7.4.2.2 NAL unit header semantics
```
Comment (chundonglinlin) [inline trunk/src/app/srs_app_gb28181.cpp:1818]: 1. Update the reference document for the annotation, page 65 was not found.
2. Should `(frame[0] & 0x7f) >> 1)` here be `(frame[0] & 0x7e) >> 1)`? It is recommended to use `SrsHevcNaluTypeParse()` consistently.

`TRANS_BY_GPT3`

File: trunk/src/app/srs_app_gb28181.cpp [hunk 3]
```diff
@@ -1764,6 +1798,182 @@ srs_error_t SrsGbMuxer::write_h264_ipb_frame(char* frame, int frame_size, uint32
...
+            }
+
+            if (h265_vps_ == vps) {
+                continue;
+            }
+
+            vps_sps_pps_change_ = true;
+            h265_vps_ = vps;
+
+            if ((err = write_h265_vps_sps_pps(dts, pts)) != srs_success) {
```
Comment (chundonglinlin) [inline trunk/src/app/srs_app_gb28181.cpp:1840]: When updating `vps`/`sps`/`pps`, the function `write_h265_vps_sps_pps` is called three times to send `rtmp header` frequently. Should we merge the calls and send `write_h265_vps_sps_pps` once?

`TRANS_BY_GPT3`

File: trunk/src/app/srs_app_gb28181.cpp [hunk 4]
```diff
@@ -1764,6 +1798,182 @@ srs_error_t SrsGbMuxer::write_h264_ipb_frame(char* frame, int frame_size, uint32
...
+srs_error_t SrsGbMuxer::write_h265_ipb_frame(char* frame, int frame_size, uint32_t dts, uint32_t pts)
+{
+    srs_error_t err = srs_success;
+
+    // when sps or pps not sent, ignore the packet.
+    if (!h265_sps_pps_sent_) {
+        return srs_error_new(ERROR_H264_DROP_BEFORE_SPS_PPS, "drop for no vps/sps/pps");
+    }
+
+    SrsHevcNaluType nt = (SrsHevcNaluType)((frame[0] & 0x7f) >> 1);
```
Comment (chundonglinlin) [inline trunk/src/app/srs_app_gb28181.cpp]: Same as above, `SrsHevcNaluTypeParse`

`TRANS_BY_GPT3`

File: trunk/src/app/srs_app_gb28181.cpp [hunk 5]
```diff
@@ -1764,6 +1798,182 @@ srs_error_t SrsGbMuxer::write_h264_ipb_frame(char* frame, int frame_size, uint32
...
+
+    // for IDR frame, the frame is keyframe.
+    SrsVideoAvcFrameType frame_type = SrsVideoAvcFrameTypeInterFrame;
+    if (nt == SrsHevcNaluType_CODED_SLICE_IDR || nt == SrsHevcNaluType_CODED_SLICE_IDR_N_LP) {
```
Comment (chundonglinlin) [inline trunk/src/app/srs_app_gb28181.cpp]: The range of values for KeyFrame is [SrsHevcNaluType_CODED_SLICE_BLA, SrsHevcNaluType_RESERVED_23].
Reference: [hevcdec.c](https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/hevcdec.c#L2897)
```
hevc_frame_start() {
    ...
    s->ref->frame->key_frame = IS_IRAP(s);
    ...
}
```

`TRANS_BY_GPT3`

File: trunk/src/app/srs_app_gb28181.hpp [hunk 6]
```diff
@@ -36,6 +36,7 @@ class SrsGbMuxer;
 class SrsSimpleRtmpClient;
 struct SrsRawAacStreamCodec;
 class SrsRawH264Stream;
+class SrsRawHEVCStream;
```
Comment (chundonglinlin) [inline trunk/src/app/srs_app_gb28181.hpp:40]: Increase macro judgment
```
#ifdef SRS_H265
class SrsRawHEVCStream;
#endif
```

`TRANS_BY_GPT3`

File: trunk/src/app/srs_app_gb28181.cpp [hunk 7]
```diff
@@ -2379,12 +2589,12 @@ srs_error_t SrsRecoverablePsContext::decode(SrsBuffer* stream, ISrsPsMessageHand
     if ((err = ctx_.decode(stream, handler)) != srs_success) {
         return enter_recover_mode(stream, handler, stream->pos(), srs_error_wrap(err, "decode pack"));
     }
-
+#ifndef SRS_H265
```
Comment (chundonglinlin) [inline trunk/src/app/srs_app_gb28181.cpp:2593]: Like this as a reference?
```
    // Check codec for H.264 and H.265.
    bool codec_ok = (codec_id == SrsVideoCodecIdAVC);
#ifdef SRS_H265
    codec_ok = codec_ok ? true : (codec_id == SrsVideoCodecIdHEVC);
#endif
    if (!codec_ok) {
         return srs_error_new();
    }
```

`TRANS_BY_GPT3`

File: trunk/src/app/srs_app_gb28181.cpp (hunk 1 above)
Comment (duiniuluantanqin) [reply trunk/src/app/srs_app_gb28181.cpp]: Modified

`TRANS_BY_GPT3`

File: trunk/src/app/srs_app_gb28181.cpp (hunk 2 above)
Comment (duiniuluantanqin) [reply trunk/src/app/srs_app_gb28181.cpp:1818]: Modified

`TRANS_BY_GPT3`

File: trunk/src/app/srs_app_gb28181.cpp (hunk 3 above)
Comment (duiniuluantanqin) [reply trunk/src/app/srs_app_gb28181.cpp:1840]: The 'write_h265_vps_sps_pps' function will be checked once, and it will only be sent if vps, sps, and pps are all not empty. So, in reality, it will only be sent once.

`TRANS_BY_GPT3`

File: trunk/src/app/srs_app_gb28181.cpp (hunk 4 above)
Comment (duiniuluantanqin) [reply trunk/src/app/srs_app_gb28181.cpp]: Modified

`TRANS_BY_GPT3`

File: trunk/src/app/srs_app_gb28181.cpp (hunk 5 above)
Comment (duiniuluantanqin) [reply trunk/src/app/srs_app_gb28181.cpp:1950]: 嗯，修改为 [SrsHevcNaluType_CODED_SLICE_BLA, SrsHevcNaluType_CODED_SLICE_CRA]

File: trunk/src/app/srs_app_gb28181.hpp (hunk 6 above)
Comment (duiniuluantanqin) [reply trunk/src/app/srs_app_gb28181.hpp:40]: Modified

`TRANS_BY_GPT3`

File: trunk/src/app/srs_app_gb28181.cpp (hunk 7 above)
Comment (duiniuluantanqin) [reply trunk/src/app/srs_app_gb28181.cpp:2593]: The `SrsTsStreamVideoHEVC` here is a type defined by the national standard `SrsTsStream`, not `SrsVideoCodecId`. So, according to your modification, the error message is not clear enough and it will increase a lot of conditional code. It may be similar to the following:
```
    // Check codec for H.264 and H.265.
    bool codec_ok = (ctx_.video_stream_type_ == SrsTsStreamVideoH264);
#ifdef SRS_H265
    codec_ok = codec_ok ? true : (ctx_.video_stream_type_ == SrsTsStreamVideoHEVC);
#endif
    if (!codec_ok) {
        if (ctx_.video_stream_type_ == SrsTsStreamVideoH264) {
            return srs_error_new(ERROR_GB_PS_HEADER, "AVC is not supported");
        } else if (ctx_.video_stream_type_ == SrsTsStreamVideoH264) {
            return srs_error_new(ERROR_GB_PS_HEADER, "HEVC is not supported");
        } else {

        }
    }
```
I feel that keeping it as it is can also work.

`TRANS_BY_GPT3`

File: trunk/src/app/srs_app_gb28181.cpp (hunk 3 above)
Comment (chundonglinlin) [reply trunk/src/app/srs_app_gb28181.cpp:1840]: After all vps, sps, and pps have values, when updating the header (usually each keyframe contains header information), which means receiving another msg (containing vps, sps, pps), will it cause three transmissions??? (send vps once + send sps once + send pps once)

`TRANS_BY_GPT3`

File: trunk/src/app/srs_app_gb28181.cpp (hunk 7 above)
Comment (chundonglinlin) [reply trunk/src/app/srs_app_gb28181.cpp:2593]: Haha, it should be like this, right?
```
    // Check codec for H.264 and H.265.
    bool codec_ok = (ctx_.video_stream_type_ == SrsTsStreamVideoH264);
#ifdef SRS_H265
    codec_ok = codec_ok ? true : (ctx_.video_stream_type_ == SrsTsStreamVideoHEVC);
#endif
    if (!codec_ok) {
        return srs_error_new(ERROR_GB_PS_HEADER, "stream_type=%d is not supported", ctx_.video_stream_type_);
    }
```

`TRANS_BY_GPT3`

File: trunk/src/app/srs_app_rtc_source.cpp [hunk 8]
```diff
@@ -974,6 +974,11 @@ srs_error_t SrsRtcFromRtmpBridge::on_video(SrsSharedPtrMessage* msg)
         return err;
     }
 
+    // WebRTC NOT support HEVC.
+    if (format->vcodec->id == SrsVideoCodecIdHEVC) {
```
Comment (chundonglinlin) [inline trunk/src/app/srs_app_rtc_source.cpp:979]: Is the supported type only determined here?

`TRANS_BY_GPT3`

Comment (duiniuluantanqin) [reply trunk/src/app/srs_app_rtc_source.cpp:979]: Only types that are not supported by WebRTC here. Or it can be changed like this:
```
if (format->vcodec->id != AVC && 
    format->vcodec->id != VP8 && 
    format->vcodec->id != VP9 && 
    format->vcodec->id != AV1 )
```
In other words, list the types that are already supported. What do you think?

`TRANS_BY_GPT3`

File: trunk/src/app/srs_app_gb28181.cpp (hunk 7 above)
Comment (duiniuluantanqin) [reply trunk/src/app/srs_app_gb28181.cpp:2593]: SrsTsStreamVideoHEVC is defined as 0x24 in the national standard. The error message would be like this: `stream_type=36 is not supported`. It doesn't seem as good as.
`HEVC is not supported`
This kind of prompt is more direct.

`TRANS_BY_GPT3`

Comment (chundonglinlin) [reply trunk/src/app/srs_app_gb28181.cpp:2593]:
```
srs_error_new(ERROR_GB_PS_HEADER, "%s is not supported", srs_ts_stream2string(ctx_.video_stream_type_));
```

File: trunk/src/app/srs_app_gb28181.cpp (hunk 3 above)
Comment (duiniuluantanqin) [reply trunk/src/app/srs_app_gb28181.cpp:1840]: This problem needs to be reorganized. The previous H264 code also had this issue, and it has already been noted.
```
    // ibp frame.
    // TODO: FIXME: we should group all frames to a rtmp/flv message from one ts message.
    srs_info("Muxer: demux avc ibp frame size=%d, dts=%d", frame_size, dts);
    if ((err = write_h264_ipb_frame(frame, frame_size, dts, pts)) != srs_success) {
```
```
    // TODO: FIMXE: there exists bug, see following comments.
    // when sps or pps changed, update the sequence header,
    // for the pps maybe not changed while sps changed.
    // so, we must check when each video ts message frame parsed.
    if (!h264_sps_changed_ || !h264_pps_changed_) {
        return err;
    }
```
See if it should be addressed in another PR or if we should solve it together.

`TRANS_BY_GPT3`

File: trunk/src/app/srs_app_rtc_source.cpp (hunk 8 above)
Comment (chundonglinlin) [reply trunk/src/app/srs_app_rtc_source.cpp:979]: 👍👍👍

File: trunk/src/app/srs_app_gb28181.cpp (hunk 3 above)
Comment (winlinvip) [reply trunk/src/app/srs_app_gb28181.cpp:1840]: If it is 264, this problem also exists. This issue only occurs when updating the SequenceHeader. Consider creating a new PR to resolve it.

`TRANS_BY_GPT3`

File: trunk/src/app/srs_app_gb28181.cpp (hunk 7 above)
Comment (duiniuluantanqin) [reply trunk/src/app/srs_app_gb28181.cpp:2593]: I previously overlooked an important issue, and this part cannot be modified yet.

When the first packet is not an `I` frame, the encoding type cannot be parsed. At this time, `video_stream_type_` is set to `SrsTsStreamReserved`, which will cause the entire `cycle` loop to exit.

`TRANS_BY_GPT3`

File: trunk/src/app/srs_app_gb28181.cpp (hunk 3 above)
Comment (duiniuluantanqin) [reply trunk/src/app/srs_app_gb28181.cpp:1840]: OK, then let's create a new PR specifically to address this issue.

`TRANS_BY_GPT3`

File: trunk/src/app/srs_app_gb28181.cpp (hunk 5 above)
Comment (duiniuluantanqin) [reply trunk/src/app/srs_app_gb28181.cpp]: OK, it has been modified.

`TRANS_BY_GPT3`

Comment (chundonglinlin) [reply trunk/src/app/srs_app_gb28181.cpp]: `IRAP (intra random access point)` see document:'

Please make sure to maintain the markdown structure.
```
F.3.29 intra random access point (IRAP) picture
ITU-T-H.265-2021.pdf, page 28.
```

`TRANS_BY_GPT3`

File: trunk/src/app/srs_app_gb28181.cpp (hunk 2 above)
Comment (chundonglinlin) [reply trunk/src/app/srs_app_gb28181.cpp:1818]: Change the name of the referenced document to `ITU-T-H.265-2021.pdf` for easy retrieval.

`TRANS_BY_GPT3`

File: trunk/src/app/srs_app_gb28181.cpp (hunk 3 above)
Comment (chundonglinlin) [reply trunk/src/app/srs_app_gb28181.cpp:1840]: `265` is implemented with new logic, should `264` be modified separately?
In fact, the header processing logic is the same as srt2rtmp,
you can refer to `SrsRtmpFromSrtBridge::on_ts_video_hevc` and `check_vps_sps_pps_change`.

`TRANS_BY_GPT3`

File: trunk/src/app/srs_app_gb28181.cpp (hunk 2 above)
Comment (duiniuluantanqin) [reply trunk/src/app/srs_app_gb28181.cpp:1818]: OK

File: trunk/src/app/srs_app_rtc_source.cpp (hunk 8 above)
Comment (duiniuluantanqin) [reply trunk/src/app/srs_app_rtc_source.cpp:979]: How about I change it like this, do you feel it will be more concise?
```
    // WebRTC NOT support HEVC.
#ifdef SRS_H265
    if (format->vcodec->id == SrsVideoCodecIdHEVC) {
        return err;
    }
#endif
```

`TRANS_BY_GPT3`

**Review by winlinvip — APPROVED** [review]

**Review by chundonglinlin — APPROVED** [review]

File: trunk/src/app/srs_app_gb28181.cpp [hunk 9]
```diff
@@ -1764,6 +1798,183 @@ srs_error_t SrsGbMuxer::write_h264_ipb_frame(char* frame, int frame_size, uint32
...
+
+    // when sps or pps not sent, ignore the packet.
+    if (!vps_sps_pps_sent_) {
+        return srs_error_new(ERROR_H264_DROP_BEFORE_SPS_PPS, "drop for no vps/sps/pps");
+    }
+
+    SrsHevcNaluType nt = SrsHevcNaluTypeParse(frame[0]);
+
+    // F.3.29 intra random access point (IRAP) picture
+    // ITU-T-H.265-2021.pdf, page 28.
```
Comment (duiniuluantanqin) [inline trunk/src/app/srs_app_gb28181.cpp:1949]: comment: F.3.29 in page 462.
> https://ossrs.io/lts/zh-cn/assets/files/ITU-T-H.265-2021-c45943bf35462dd9b8a9c5afc19df5da.pdf
