### PR TITLE
Reverted: WHIP: Fix bug for converting WHIP to RTMP/HLS. v5.0.204 v6.0.107

### LINKED ISSUE #3583: WHIP: OBS playback fails if attempted before publishing.
Reproduce steps:

1. Run SRS with rtc.conf
2. Play stream by WHEP http://localhost:8080/players/whep.html
3. Publish OBS by WHIP.

The stream could not be played. Visit `chrome://webrtc-internals/` to see the increasing PLI count, and note that there are no decoded video packets.

### PR DESCRIPTION
**Pull request by winlinvip**
1. When converting RTC to RTMP, it is necessary to synchronize the audio and video timestamps. When the synchronization status changes, whether it is unsynchronized or synchronized, print logs to facilitate troubleshooting of such issues.
2. Chrome uses the STAP-A packet, which means a single RTP packet contains SPS/PPS information. OBS WHIP, on the other hand, sends SPS and PPS in separate RTP packets. Therefore, SPS and PPS are in two independent RTP packets, and SRS needs to cache these two packets.

---------

Co-authored-by: john <hondaxiao@tencent.com>

### CODE REVIEW

**Comment by winlinvip** [comment]
Merge into versions 5.0 and 6.0.

`TRANS_BY_GPT4`

File: trunk/src/app/srs_app_rtc_source.cpp [hunk 1]
```diff
@@ -1499,46 +1513,71 @@ srs_error_t SrsRtcFrameBuilder::packet_video_key_frame(SrsRtpPacket* pkt)
...
+    if (raw_payload) {
+        if (pkt->nalu_type == SrsAvcNaluTypeSPS) {
+            srs_freep(obs_whip_sps_);
+            obs_whip_sps_ = pkt->copy();
+        } else if (pkt->nalu_type == SrsAvcNaluTypePPS) {
+            srs_freep(obs_whip_pps_);
+            obs_whip_pps_ = pkt->copy();
+        }
+        // Ignore if one of OBS WHIP SPS/PPS is not ready.
+        if ((obs_whip_sps_ && !obs_whip_pps_) || (obs_whip_sps_ && !obs_whip_pps_)) {
```
Comment (xiaozhihong) [inline trunk/src/app/srs_app_rtc_source.cpp]: if (! obs_whip_sps_ || ! obs_whip_pps_)

File: trunk/src/app/srs_app_rtc_source.cpp [hunk 2]
```diff
@@ -1499,46 +1513,71 @@ srs_error_t SrsRtcFrameBuilder::packet_video_key_frame(SrsRtpPacket* pkt)
...
-            std::string sh;
-            SrsRawH264Stream* avc = new SrsRawH264Stream();
-            SrsAutoFree(SrsRawH264Stream, avc);
+        }
 
-            if ((err = avc->mux_sequence_header(string(sps->bytes, sps->size), string(pps->bytes, pps->size), sh)) != srs_success) {
-                return srs_error_wrap(err, "mux sequence header");
-            }
+        // Reset SPS/PPS cache.
+        SrsAutoFree(SrsRtpPacket, obs_whip_sps_);
```
Comment (xiaozhihong) [inline trunk/src/app/srs_app_rtc_source.cpp:1547]: There is no need to release; it can be reused continuously without refreshing.

`TRANS_BY_GPT4`

File: trunk/src/app/srs_app_rtc_source.cpp (hunk 1 above)
Comment (winlinvip) [reply trunk/src/app/srs_app_rtc_source.cpp]: Fixed.

File: trunk/src/app/srs_app_rtc_source.cpp (hunk 2 above)
Comment (winlinvip) [reply trunk/src/app/srs_app_rtc_source.cpp:1547]: If not released, then upon the next refresh of SPS (Sequence Parameter Set) and PPS (Picture Parameter Set), receiving either SPS or PPS will trigger the generation of a sequence header, instead of waiting for both SPS and PPS to be received before refreshing.

`TRANS_BY_GPT4`

**Review by xiaozhihong — APPROVED** [review]

**Comment by winlinvip** [comment]
Please be aware that this merge request has been revoked due to issues after merging into 5.0. The pull request has been resubmitted: https://github.com/ossrs/srs/pull/3920

`TRANS_BY_GPT4`
