### PR TITLE
rtmp2rtc: Support RTMP-to-WebRTC conversion with HEVC. v7.0.33

### LINKED ISSUE #4178: WebRTC: Chrome HEVC support
SRS 6.0 already supports a lot HEVC functions, but not RTMP2WebRTC because Chrome/FireFox don't support HECV in WebRTC.

From current report, Chrome will launch the feature to support HEVC in WebRTC (https://issues.chromium.org/issues/341986313).
Is there any plan for SRS to support RTMP2WebRTC in HEVC? Thanks!

### LINKED ISSUE #4248: [Help] How to multistream HEVC with OBS?
How can i multistream to YouTube and Twitch using OBS HEVC over rtmp on windows? Does anyone know? I dont kmow How to use SRS, i was using Nginx-rtmp-module before to push a H264 stream to both platforms, but It doesn't work with HEVC. Thanks in advance!

### LINKED ISSUE #4259: WebRTC is unable to play video streams in the H.265 format.
**Describe the bug**
WebRTC is unable to play video streams in the H265 format.

**Version**
The version of SRS is 6.0.48.

**To Reproduce**
1. ./configure --gb28181=on --h265=on
2. make
3. /objs/srs -c conf/push.gb28181.conf 

**Expected behavior**

The Safire browser is capable of playing H.265 format videos.

**Screenshots**
image
image

**Additional context**
Viewing the printed data in the console, the generated offer in the Safire browser's SDP includes H.265 format within the 'm=video' section. However, after receiving the answer, the selected format is still H.264.

**Screenshots**
image
image
image

**Additional context**

`TRANS_BY_GPT4`

### LINKED ISSUE #4263: Does SRS support push HEVC/H.265 over WebRTC(whip) using OBS ?
**Describe the bug**
Does SRS support push HEVC/H.265 over WebRTC using OBS ? I don't know whether SRS or OBS does not support push HEVC/H.265 over WebRTC ?

**Version**
SRS 6.0.155

### PR DESCRIPTION
**Pull request by duiniuluantanqin**
## Usage

Launch Chrome with H.265 enabled: 

Upgrade to the latest Chrome browser (version 136) fully enables this by default, so there's no need to launch it with any extra parameters.

Launch SRS with `rtmp2rtc.conf`

```bash
./objs/srs -c conf/rtmp2rtc.conf
```

Push RTMP with H.265 codec, without B frame:

```bash
ffmpeg -stream_loop -1 -re -i doc/source.flv \
  -c:v libx265 -profile:v main -preset fast -b:v 2000k -maxrate 2000k -bufsize 2000k -bf 0 \
  -c:a aac -b:a 48k -ar 44100 -ac 2 -f flv rtmp://localhost/live/livestream
```

Play with WebRTC: http://localhost:8080/players/whep.html?schema=http&&codec=hevc

image

---------

Co-authored-by: chundonglinlin <chundonglinlin@163.com>
Co-authored-by: winlin <winlinvip@gmail.com>
Co-authored-by: john <hondaxiao@tencent.com>

### CODE REVIEW

File: trunk/src/kernel/srs_kernel_rtc_rtp.hpp [hunk 1]
```diff
@@ -460,4 +466,68 @@ class SrsRtpFUAPayload2 : public ISrsRtpPayloader
...
+    virtual ~SrsRtpFUAPayloadHevc();
+// interface ISrsRtpPayloader
+public:
+    virtual uint64_t nb_bytes();
+    virtual srs_error_t encode(SrsBuffer* buf);
+    virtual srs_error_t decode(SrsBuffer* buf);
+    virtual ISrsRtpPayloader* copy();
+};
+
+// FU-A, for one NALU with multiple fragments.
```
Comment (suzp1984) [inline trunk/src/kernel/srs_kernel_rtc_rtp.hpp]: https://datatracker.ietf.org/doc/html/rfc7798#section-4.4.3

According to this doc, there is only one kind of Fragmentation Unit. 
There are no FU-A or FU-B types.

File: trunk/src/kernel/srs_kernel_rtc_rtp.cpp [hunk 2]
```diff
@@ -1522,3 +1539,361 @@ ISrsRtpPayloader* SrsRtpFUAPayload2::copy()
...
+srs_error_t SrsRtpFUAPayloadHevc2::encode(SrsBuffer* buf)
+{
+    if (!buf->require(3 + size)) {
+        return srs_error_new(ERROR_RTC_RTP_MUXER, "requires %d bytes", 3 + size);
+    }
+
+    // Fast encoding.
+    char* p = buf->head();
+
+    // FU indicator, @see: https://datatracker.ietf.org/doc/html/rfc7798#section-4.4.3
```
Comment (suzp1984) [inline trunk/src/kernel/srs_kernel_rtc_rtp.cpp]: `FU indicator` is the h.264 rtp payload header term (https://datatracker.ietf.org/doc/html/rfc6184#section-5.8).
For h.265, it is `PayloadHdr` (https://datatracker.ietf.org/doc/html/rfc7798#section-4.4.3), the `PayloadHdr` struct can be see https://datatracker.ietf.org/doc/html/rfc7798#section-1.1.4.

File: trunk/src/kernel/srs_kernel_rtc_rtp.hpp [hunk 3]
```diff
@@ -254,8 +258,10 @@ enum SrsRtspPacketPayloadType
     SrsRtspPacketPayloadTypeRaw,
     SrsRtspPacketPayloadTypeFUA2,
     SrsRtspPacketPayloadTypeFUA,
+    SrsRtspPacketPayloadTypeFUAHevc,
```
Comment (suzp1984) [inline trunk/src/kernel/srs_kernel_rtc_rtp.hpp:262]: Is the `*Rtsp*` part of the removed RTSP related code? Is it should be renamed to `SrsRtpPacketPayloadType`?

File: trunk/src/kernel/srs_kernel_rtc_rtp.cpp [hunk 4]
```diff
@@ -1061,10 +1078,10 @@ void SrsRtpRawNALUs::push_back(SrsSample* sample)
     nalus.push_back(sample);
 }
 
-uint8_t SrsRtpRawNALUs::skip_first_byte()
+uint8_t SrsRtpRawNALUs::skip_bytes(int count)
 {
     srs_assert (cursor >= 0 && nn_bytes > 0 && cursor < nn_bytes);
```
Comment (suzp1984) [inline trunk/src/kernel/srs_kernel_rtc_rtp.cpp]: `srs_assert(.... && cursor + count < nn_byptes)`?

assert earlier before `SrsRtpRawNALUs::read_samples`?

File: trunk/src/app/srs_app_rtc_source.cpp [hunk 5]
```diff
@@ -1298,12 +1319,34 @@ srs_error_t SrsRtcRtpBuilder::package_nalus(SrsSharedPtrMessage* msg, const vect
             pkt->header.set_sequence(video_sequence++);
             pkt->header.set_timestamp(msg->timestamp * 90);
 
-            fua->nri = (SrsAvcNaluType)header;
-            fua->nalu_type = (SrsAvcNaluType)nal_type;
-            fua->start = bool(i == 0);
-            fua->end = bool(i == num_of_packet - 1);
+            if (is_hevc) {
+                uint8_t nal_type = SrsHevcNaluTypeParse(header);
```
Comment (suzp1984) [inline trunk/src/app/srs_app_rtc_source.cpp]: `#define SrsHevcNaluTypeParse(code) (SrsHevcNaluType)((code & 0x7E) >> 1)`

the `SrsHevcNaluTypeParse` macro already define the type. 
So assign `fua->nalu_type = SrsHevcNaluTypeParse(header)`.

File: trunk/src/app/srs_app_rtc_source.cpp [hunk 6]
```diff
@@ -1298,12 +1319,34 @@ srs_error_t SrsRtcRtpBuilder::package_nalus(SrsSharedPtrMessage* msg, const vect
...
+                    srs_freep(fua);
+                    return srs_error_wrap(err, "read samples %d bytes, left %d, total %d", packet_size, nb_left, nn_bytes);
+                }
+                fua->nalu_type = (SrsHevcNaluType)nal_type;
+                fua->start = bool(i == 0);
+                fua->end = bool(i == num_of_packet - 1);
+
+                pkt->set_payload(fua, SrsRtspPacketPayloadTypeFUAHevc);
+            } else {
+                uint8_t nal_type = header & kNalTypeMask;
```
Comment (suzp1984) [inline trunk/src/app/srs_app_rtc_source.cpp]: why not add another macro to parse `AvcNaluType`:

`#define SrsAvcNaluTypeParse(code) (SrsAvcNaluType)(code & kNalTypeMask)`

File: trunk/src/kernel/srs_kernel_codec.hpp [hunk 7]
```diff
@@ -498,6 +499,12 @@ enum SrsHevcNaluType {
 };
 #define SrsHevcNaluTypeParse(code) (SrsHevcNaluType)((code & 0x7E) >> 1)
```
Comment (suzp1984) [inline trunk/src/kernel/srs_kernel_codec.hpp:508]: It take me a while to find the h.265 nalu header definition.
so, add the document reference here?
`@see https://datatracker.ietf.org/doc/html/rfc7798#section-1.1.4`

File: trunk/src/app/srs_app_rtc_conn.cpp [hunk 8]
```diff
@@ -2598,6 +2598,51 @@ bool srs_sdp_has_h264_profile(const SrsSdp& sdp, const string& profile)
...
+{
+    srs_error_t err = srs_success;
+
+    if (payload_type.format_specific_param_.empty()) {
+        return false;
+    }
+
+    H265SpecificParam h265_param;
+    if ((err = srs_parse_h265_fmtp(payload_type.format_specific_param_, h265_param)) != srs_success) {
+        srs_error_reset(err);
```
Comment (suzp1984) [inline trunk/src/app/srs_app_rtc_conn.cpp:2611]: maybe print the err message as `warn` logs here?

File: trunk/src/app/srs_app_rtc_conn.cpp [hunk 9]
```diff
@@ -2598,6 +2598,51 @@ bool srs_sdp_has_h264_profile(const SrsSdp& sdp, const string& profile)
...
+    }
+
+    if (h265_param.profile_id == profile) {
+        return true;
+    }
+
+    return false;
+}
+
+bool srs_sdp_has_h265_profile(const SrsSdp& sdp, const string& profile)
```
Comment (suzp1984) [inline trunk/src/app/srs_app_rtc_conn.cpp:2622]: this is a so general method, the `profile-id` defined in h.265 standard, but just main profile(1), main 10 profile(2), and main still picture profile(3) are commonly used.

why not add more specific wrapper method. e.g. `srs_sdp_has_h265_main_profile(const SrsSdp& sdp)`, 
`srs_sdp_has_h265_main_10_profile(sdp)` and `srs_sdp_has_h265_main_still_picture_profile(sdp)`.

File: trunk/src/kernel/srs_kernel_rtc_rtp.cpp (hunk 2 above)
Comment (duiniuluantanqin) [reply trunk/src/kernel/srs_kernel_rtc_rtp.cpp]: Yes, should change name from indicator to PayloadHdr

File: trunk/src/kernel/srs_kernel_rtc_rtp.hpp (hunk 3 above)
Comment (duiniuluantanqin) [reply trunk/src/kernel/srs_kernel_rtc_rtp.hpp:262]: maybe it is a typo introduced  by @winlinvip

File: trunk/src/kernel/srs_kernel_rtc_rtp.cpp (hunk 4 above)
Comment (duiniuluantanqin) [reply trunk/src/kernel/srs_kernel_rtc_rtp.cpp]: Yeah

File: trunk/src/app/srs_app_rtc_source.cpp (hunk 5 above)
Comment (duiniuluantanqin) [reply trunk/src/app/srs_app_rtc_source.cpp]: Yeah

File: trunk/src/app/srs_app_rtc_source.cpp (hunk 6 above)
Comment (duiniuluantanqin) [reply trunk/src/app/srs_app_rtc_source.cpp]: fixed

File: trunk/src/kernel/srs_kernel_codec.hpp (hunk 7 above)
Comment (duiniuluantanqin) [reply trunk/src/kernel/srs_kernel_codec.hpp:508]: Yeah

File: trunk/src/app/srs_app_rtc_source.cpp [hunk 10]
```diff
@@ -1359,17 +1410,34 @@ srs_error_t SrsRtcRtpBuilder::package_fu_a(SrsSharedPtrMessage* msg, SrsSample*
         pkt->frame_type = SrsFrameTypeVideo;
         pkt->header.set_sequence(video_sequence++);
         pkt->header.set_timestamp(msg->timestamp * 90);
+        pkt->nalu_type = is_hevc ? (SrsAvcNaluType)kFuAHevc : (SrsAvcNaluType)kFuA;
```
Comment (suzp1984) [inline trunk/src/app/srs_app_rtc_source.cpp]: https://github.com/ossrs/srs/blob/13597d1b7f28465dc5150eeb04ba6c52899e9ac9/trunk/src/kernel/srs_kernel_rtc_rtp.hpp#L292

The `nalu_type` of `SrsRtpPacket` is still `SrsAvcNaluType`, it seems improperly now. I would suggest raw `unit8_t` .

File: trunk/src/kernel/srs_kernel_rtc_rtp.cpp [hunk 11]
```diff
@@ -1522,3 +1539,361 @@ ISrsRtpPayloader* SrsRtpFUAPayload2::copy()
...
+}
+
+srs_error_t SrsRtpFUAPayloadHevc::decode(SrsBuffer* buf)
+{
+    if (!buf->require(3)) {
+        return srs_error_new(ERROR_RTC_RTP_MUXER, "requires %d bytes", 3);
+    }
+
+    uint8_t payload_hdr1 = buf->read_1bytes();
+    uint8_t payload_hdr2 = buf->read_1bytes();
```
Comment (suzp1984) [inline trunk/src/kernel/srs_kernel_rtc_rtp.cpp]: unused variables: `payload_hdr1` and `payload_hdr2`.

File: trunk/src/kernel/srs_kernel_rtc_rtp.cpp [hunk 12]
```diff
@@ -1522,3 +1539,361 @@ ISrsRtpPayloader* SrsRtpFUAPayload2::copy()
...
+}
+
+srs_error_t SrsRtpFUAPayloadHevc2::decode(SrsBuffer* buf)
+{
+    if (!buf->require(3)) {
+        return srs_error_new(ERROR_RTC_RTP_MUXER, "requires 3 bytes");
+    }
+
+    uint8_t payload_hdr1 = buf->read_1bytes();
+    uint8_t payload_hdr2 = buf->read_1bytes();
```
Comment (suzp1984) [inline trunk/src/kernel/srs_kernel_rtc_rtp.cpp]: another two unused variables: `payload_hdr1` and `payload_hdr2`.

File: trunk/src/app/srs_app_rtc_source.cpp [hunk 13]
```diff
@@ -1149,10 +1154,16 @@ srs_error_t SrsRtcRtpBuilder::filter(SrsSharedPtrMessage* msg, SrsFormat* format
 
         // Because RTC does not support B-frame, so we will drop them.
         // TODO: Drop B-frame in better way, which not cause picture corruption.
-        if (!keep_bframe && format->vcodec->id == SrsVideoCodecIdAVC) {
+        if (!keep_bframe) {
             bool is_b_frame;
-            if ((err = SrsVideoFrame::parse_avc_b_frame(sample, is_b_frame)) != srs_success) {
-                return srs_error_wrap(err, "parse bframe");
+            if (format->vcodec->id == SrsVideoCodecIdAVC) {
```
Comment (suzp1984) [inline trunk/src/app/srs_app_rtc_source.cpp:1179]: compiler warning: if format->vcodec->id is either AVC nor HEVC, then `is_b_frame` is uninitialized, so consider this case, always initialize the var `is_b_frame`.
`bool is_b_frame = false;`

File: trunk/src/kernel/srs_kernel_rtc_rtp.hpp (hunk 1 above)
Comment (duiniuluantanqin) [reply trunk/src/kernel/srs_kernel_rtc_rtp.hpp]: Yeah

File: trunk/src/app/srs_app_rtc_conn.cpp (hunk 8 above)
Comment (duiniuluantanqin) [reply trunk/src/app/srs_app_rtc_conn.cpp:2611]: it might generate a lot of unnecessary logs, because in a loop

File: trunk/src/app/srs_app_rtc_conn.cpp (hunk 9 above)
Comment (duiniuluantanqin) [reply trunk/src/app/srs_app_rtc_conn.cpp:2622]: To align with H264, and we can improve it in another PR.

File: trunk/src/app/srs_app_rtc_source.cpp (hunk 10 above)
Comment (duiniuluantanqin) [reply trunk/src/app/srs_app_rtc_source.cpp]: agree with you

File: trunk/src/kernel/srs_kernel_rtc_rtp.cpp (hunk 11 above)
Comment (duiniuluantanqin) [reply trunk/src/kernel/srs_kernel_rtc_rtp.cpp]: fixed

File: trunk/src/kernel/srs_kernel_rtc_rtp.cpp (hunk 12 above)
Comment (duiniuluantanqin) [reply trunk/src/kernel/srs_kernel_rtc_rtp.cpp]: fixed

File: trunk/src/app/srs_app_rtc_source.cpp (hunk 13 above)
Comment (duiniuluantanqin) [reply trunk/src/app/srs_app_rtc_source.cpp:1179]: ok

File: trunk/src/app/srs_app_rtc_source.cpp [hunk 14]
```diff
@@ -2070,6 +2136,33 @@ SrsMediaPayloadType SrsVideoPayload::generate_media_payload_type()
...
+    media_payload_type.encoding_name_ = name_;
+    media_payload_type.clock_rate_ = sample_;
+    media_payload_type.rtcp_fb_ = rtcp_fbs_;
+
+    std::ostringstream format_specific_param;
+    if (!h265_param_.level_id.empty()) {
+        format_specific_param << "level-id=" << h265_param_.level_id;
+    }
+    if (!h265_param_.profile_id.empty()) {
+        format_specific_param << ";profile-id=" << h265_param_.profile_id;
```
Comment (suzp1984) [inline trunk/src/app/srs_app_rtc_source.cpp]: if the `level_id` is empty, the `format_specific_param will output with `;` ahead. 
Is this case possible?

File: trunk/src/app/srs_app_rtc_source.cpp [hunk 15]
```diff
@@ -2107,6 +2200,31 @@ srs_error_t SrsVideoPayload::set_h264_param_desc(std::string fmtp)
...
+srs_error_t SrsVideoPayload::set_h265_param_desc(std::string fmtp)
+{
+    std::vector<std::string> attributes = split_str(fmtp, ";");
+    for (size_t i = 0; i < attributes.size(); ++i) {
+        std::string attribute = attributes.at(i);
+        std::vector<std::string> kv = split_str(attribute, "=");
+        if (kv.size() != 2) {
+            return srs_error_new(ERROR_RTC_SDP_DECODE, "invalid h265 param=%s", attribute.c_str());
+        }
+        if (kv[0] == "level-id") {
```
Comment (suzp1984) [inline trunk/src/app/srs_app_rtc_source.cpp:2254]: I didn't read the SDP spec, but only asked the AI whether the SDP parameters case sensitive?

It said the SDP parameters are generally case-insensitive. But the best practice is to use consistent casing, so it has some conventions there, e.g. 
```
a=rtpmap:96 H264/90000
a=fmtp:96 profile-level-id=42e01f; packetization-mode=1
```
* `H264` and `h264` are equivalent. (srs already handle this, I do think so)
* `profile-level-id` and `PROFILE-LEVEL-ID` are equivalent. (srs not handle this case here at least).
* the whitespace between parameters. (e.g. profile-level-id=42e01f;`_`packetization-mode=1).

File: trunk/src/app/srs_app_rtc_conn.cpp [hunk 16]
```diff
@@ -3083,56 +3126,87 @@ srs_error_t SrsRtcConnection::negotiate_play_capability(SrsRtcUserConfig* ruc, s
...
+                    // Format example: level-id=180;profile-id=1;tier-flag=0;tx-mode=SRST
+                    if (!has_main_profile || srs_sdp_has_h265_profile(payload, "1")) {
+                        remote_payload = payload;
+                        break;
+                    }
+                }
 
-            // TODO: FIXME: pick up a profile for HEVC.
-            // @see https://www.rfc-editor.org/rfc/rfc7798#section-7.2.1
+                track_descs = source->get_track_desc("video", "H265");
```
Comment (suzp1984) [inline trunk/src/app/srs_app_rtc_conn.cpp:3186]: About this method `get_track_desc`, I would suggest for refactor later.
* there are only 3 kinds of track types `audio`, `video`, `data`, the SRS only has 2 of them, `audio/video`. A `enum` is much better here. 
* Inside `get_track_desc`, there is a hide precondition of the `media_name`, the audio codec name is lower casing, while the video codec name is upper case. This method did the force case transform for the stored media, but forget do same transform for the `media_name` parameter.

**Review by suzp1984 — COMMENTED** [review]
About the SDP parameter and codec name case sensitive issues.

File: trunk/src/app/srs_app_rtc_source.cpp (hunk 14 above)
Comment (duiniuluantanqin) [reply trunk/src/app/srs_app_rtc_source.cpp]: fixed

File: trunk/src/app/srs_app_rtc_source.cpp (hunk 15 above)
Comment (duiniuluantanqin) [reply trunk/src/app/srs_app_rtc_source.cpp:2254]: It appears the protocol does not explicitly state whether spaces are allowed, but based on experience, they are not used.

File: trunk/src/app/srs_app_rtc_conn.cpp (hunk 16 above)
Comment (duiniuluantanqin) [reply trunk/src/app/srs_app_rtc_conn.cpp:3186]: That's true. I've also been affected by this when doing case conversions. We can solve this problem with another PR

**Comment by chundonglinlin** [comment]
Currently Safari supports rtc2rtc. We should test the performance in Safari browser. I haven't run rtmp2rtc in Safari yet.

**Comment by suzp1984** [comment]
## Case 1:
1. Publish RTC by WHIP: `http://localhost:1985/rtc/v1/whip/?app=live&stream=livestream&codec=hevc`, (I used safari), the SRS will gives answer offer with `h265` codec. 
2. But if publish RTC by `&codec=h265`, the SRS will gives me `h264` as offer answer. 
**Expect**: improve WHIP/WHEP api to more flexible. (recognize both `hevc`, `h265`, `h.265`?)

## Case 2:
1. Publish RTC by WHIP: `http://localhost:1985/rtc/v1/whip/?app=live&stream=livestream&codec=hevc` (safari in my case), 
2. Play the RTC by WHEP: `http://localhost:1985/rtc/v1/whep/?app=live&stream=livestream` (chrome in my case), H.265 streams play in web browser well. 
3. Then I play rtmp bridged stream: `ffplay rmtp://localhost/live/livestream`, it plays well too, but with `h.264` codec shows in the `ffprobe rtmp://localhost/live/livestream`. 

So I think the **rtc to rtmp bridge** not consider this case well.

## Case 3: 
1. Publish RTC by WHIP: `http://localhost:1985/rtc/v1/whip/?app=live&stream=livestream&codec=hevc` (safari)
2. Play RTC by WHEP: `http://localhost:1985/rtc/v1/whep/?app=live&stream=livestream&codec=h264` (chrome)
3. The WHEP api return the answer offer without video media track, and chrome also didn't play the audio also.
**Expect**: WHEP api should return error code in this case.

**Comment by chundonglinlin** [comment]
> ## Case 1:
> 1. Publish RTC by WHIP: `http://localhost:1985/rtc/v1/whip/?app=live&stream=livestream&codec=hevc`, (I used safari), the SRS will gives answer offer with `h265` codec.
> 2. But if publish RTC by `&codec=h265`, the SRS will gives me `h264` as offer answer.
>    **Expect**: improve WHIP/WHEP api to more flexible. (recognize both `hevc`, `h265`, `h.265`?)
> 
> ## Case 2:
> 1. Publish RTC by WHIP: `http://localhost:1985/rtc/v1/whip/?app=live&stream=livestream&codec=hevc` (safari in my case),
> 2. Play the RTC by WHEP: `http://localhost:1985/rtc/v1/whep/?app=live&stream=livestream` (chrome in my case), H.265 streams play in web browser well.
> 3. Then I play rtmp bridged stream: `ffplay rmtp://localhost/live/livestream`, it plays well too, but with `h.264` codec shows in the `ffprobe rtmp://localhost/live/livestream`.
> 
> So I think the **rtc to rtmp bridge** not consider this case well.
> 
> ## Case 3:
> 1. Publish RTC by WHIP: `http://localhost:1985/rtc/v1/whip/?app=live&stream=livestream&codec=hevc` (safari)
> 2. Play RTC by WHEP: `http://localhost:1985/rtc/v1/whep/?app=live&stream=livestream&codec=h264` (chrome)
> 3. The WHEP api return the answer offer without video media track, and chrome also didn't play the audio also.
>    **Expect**: WHEP api should return error code in this case.

I think this PR only supports hevc by rtmp2rtc, hevc by rtc2rtc can be fixed in the new PR.

**Comment by duiniuluantanqin** [comment]
@suzp1984 rtc to rtmp is NOT support by now, I will start working on this after the PR is merged.

**Review by suzp1984 — APPROVED** [review]

**Comment by chundonglinlin** [comment]
> Currently Safari supports rtc2rtc. We should test the performance in Safari browser. I haven't run rtmp2rtc in Safari yet.

We should test WebRTC 265 on Safari 18.0 and above.
Source: WebKit Features in Safari 18.0 - WebRTC (https://webkit.org/blog/15865/webkit-features-in-safari-18-0/#webrtc)

`TRANS_BY_GPT4`

File: trunk/src/app/srs_app_rtc_source.cpp [hunk 17]
```diff
@@ -1083,6 +1084,10 @@ srs_error_t SrsRtcRtpBuilder::on_video(SrsSharedPtrMessage* msg)
     if (has_idr) {
         SrsUniquePtr<SrsRtpPacket> pkt(new SrsRtpPacket());
 
+        if ((err = bridge_->update_codec(format->vcodec->id)) != srs_success) {
```
Comment (chundonglinlin) [inline trunk/src/app/srs_app_rtc_source.cpp]: Each keyframe invokes the `source_->get_track_desc` method, which could be moved to the initialization section.

`TRANS_BY_GPT4`

Comment (duiniuluantanqin) [reply trunk/src/app/srs_app_rtc_source.cpp]: There's a problem with this modification: the URL must specify "codec=hevc."  I would prefer that the client side not have to worry about the encoding format.

Comment (chundonglinlin) [reply trunk/src/app/srs_app_rtc_source.cpp]: You're right, follow your requirements.

Comment (duiniuluantanqin) [reply trunk/src/app/srs_app_rtc_source.cpp]: ok

File: trunk/src/kernel/srs_kernel_codec.cpp [hunk 18]
```diff
@@ -721,7 +721,7 @@ srs_error_t SrsVideoFrame::parse_avc_b_frame(const SrsSample* sample, bool& is_b
         return srs_error_wrap(err, "parse avc nalu type error");
     }
 
-    if (nalu_type != SrsAvcNaluTypeNonIDR && nalu_type != SrsAvcNaluTypeDataPartitionA && nalu_type != SrsAvcNaluTypeIDR) {
+    if (nalu_type != SrsAvcNaluTypeNonIDR && nalu_type != SrsAvcNaluTypeDataPartitionA) {
```
Comment (suzp1984) [inline trunk/src/kernel/srs_kernel_codec.cpp]: This line said the b-frame only exist in Non-IDR, Data PartitionA and IDR Nal unit, and this PR said the b-frame can not exist in IDR Nal unit. So I know the answer is in the ISO_IEC_14496-10-AVC-2012.pdf. I just can't found it yet, need more time to understand the AVC spec.

File: trunk/src/utest/srs_utest_kernel.cpp [hunk 19]
```diff
@@ -3567,6 +3567,204 @@ VOID TEST(KernelCodecTest, AVFrameNoConfig)
...
+        // PPS
+        uint8_t data4[] = {0x08, 0xA8, 0x00, 0x00};
+        SrsSample sample4((char*)data4, sizeof(data4));
+        
+        is_b_frame = true;
+        HELPER_EXPECT_SUCCESS(SrsVideoFrame::parse_avc_b_frame(&sample4, is_b_frame));
+        EXPECT_FALSE(is_b_frame);
+
+        // IDR
+        uint8_t data5[] = {0x05, 0xA8, 0x00, 0x00};
```
Comment (suzp1984) [inline trunk/src/utest/srs_utest_kernel.cpp:3646]: Is this UT indicate that IDR Nal unit can not contain any b-frame? How do you get this test data?

File: trunk/src/kernel/srs_kernel_codec.cpp (hunk 18 above)
Comment (duiniuluantanqin) [reply trunk/src/kernel/srs_kernel_codec.cpp]: IDR frames and B-frames should be mutually exclusive, right?

`TRANS_BY_GPT4`

File: trunk/src/utest/srs_utest_kernel.cpp (hunk 19 above)
Comment (duiniuluantanqin) [reply trunk/src/utest/srs_utest_kernel.cpp:3646]: This situation should never occur. Therefore, the following line of code will not trigger an error; it would only theoretically cause ambiguity.
```
if (nalu_type != SrsAvcNaluTypeNonIDR && nalu_type != SrsAvcNaluTypeDataPartitionA && nalu_type != SrsAvcNaluTypeIDR)
```

`TRANS_BY_GPT4`

File: trunk/src/kernel/srs_kernel_codec.cpp (hunk 18 above)
Comment (suzp1984) [reply trunk/src/kernel/srs_kernel_codec.cpp]: IDR Nal unit is for I-frame slices, which are decoded independently without any dependency. So It should not contain any B-frame slices. It make sense. 
Search more info about Nalu Type Data Partition A.

Comment (suzp1984) [reply trunk/src/kernel/srs_kernel_codec.cpp]: > IDR frames and B-frames should be mutually exclusive

Literally, Yes.

Comment (suzp1984) [reply trunk/src/kernel/srs_kernel_codec.cpp]: ISO_IEC_14496-10-AVC-2012.pdf, or AVC/h.264 data coding is hard for understanding, is there any more junior level docs about the avc data layout docs?

Now, I'm wonder what Nalu type Data Partition A, B, C are? Are they can be the container of b-frame slices also?

Comment (duiniuluantanqin) [reply trunk/src/kernel/srs_kernel_codec.cpp]: Data partitions A, B, and C indeed contain B-frames.

`TRANS_BY_GPT4`

Comment (suzp1984) [reply trunk/src/kernel/srs_kernel_codec.cpp]: So, add SrsAvcNaluTypeDataPartitionB & SrsAvcNaluTypeDataPartitionC?

Comment (duiniuluantanqin) [reply trunk/src/kernel/srs_kernel_codec.cpp]: should be

Comment (duiniuluantanqin) [reply trunk/src/kernel/srs_kernel_codec.cpp]: fixed

File: trunk/src/app/srs_app_rtc_conn.cpp [hunk 20]
```diff
@@ -3083,56 +3126,87 @@ srs_error_t SrsRtcConnection::negotiate_play_capability(SrsRtcUserConfig* ruc, s
...
-            if (payloads.empty()) {
-                return srs_error_new(ERROR_RTC_SDP_EXCHANGE, "no found valid AV1 payload type");
+        } else if (remote_media_desc.is_video()) {
+            std::string prefer_codec = ruc->codec_; 
+            if (prefer_codec.empty()) {
+                // Get the source codec if not specified.
+                std::vector<SrsRtcTrackDescription*> track_descs = source->get_track_desc("video", "");
+                if (!track_descs.empty()) {
+                    std::string codec_name = track_descs.at(0)->media_->name_;
+                    std::transform(codec_name.begin(), codec_name.end(), codec_name.begin(), ::tolower);
```
Comment (xiaozhihong) [inline trunk/src/app/srs_app_rtc_conn.cpp:3136]: Is C98 incompatible?

`TRANS_BY_GPT4`

File: trunk/src/app/srs_app_stream_bridge.cpp [hunk 21]
```diff
@@ -155,6 +157,45 @@ srs_error_t SrsFrameToRtcBridge::on_rtp(SrsRtpPacket* pkt)
 {
     return source_->on_rtp(pkt);
 }
+
+srs_error_t SrsFrameToRtcBridge::update_codec(SrsVideoCodecId id)
```
Comment (xiaozhihong) [inline trunk/src/app/srs_app_stream_bridge.cpp:161]: This function seems to be of little use. It appears that there is no need to update the codec, or perhaps a different timing should be chosen for the update. Moreover, if an update is required when transitioning from H.264 to H.265, what about the case when transitioning from H.265 to H.264?

`TRANS_BY_GPT4`

File: trunk/src/app/srs_app_rtc_source.cpp [hunk 22]
```diff
@@ -1149,10 +1164,16 @@ srs_error_t SrsRtcRtpBuilder::filter(SrsSharedPtrMessage* msg, SrsFormat* format
...
         // TODO: Drop B-frame in better way, which not cause picture corruption.
-        if (!keep_bframe && format->vcodec->id == SrsVideoCodecIdAVC) {
-            bool is_b_frame;
-            if ((err = SrsVideoFrame::parse_avc_b_frame(sample, is_b_frame)) != srs_success) {
-                return srs_error_wrap(err, "parse bframe");
+        if (!keep_bframe) {
+            bool is_b_frame = false;
+            if (format->vcodec->id == SrsVideoCodecIdAVC) {
+                if ((err = SrsVideoFrame::parse_avc_b_frame(sample, is_b_frame)) != srs_success) {
+                    return srs_error_wrap(err, "parse bframe");
```
Comment (xiaozhihong) [inline trunk/src/app/srs_app_rtc_source.cpp:1181]: is "parse avc bframe " better?

File: trunk/src/app/srs_app_rtc_source.cpp [hunk 23]
```diff
@@ -1149,10 +1164,16 @@ srs_error_t SrsRtcRtpBuilder::filter(SrsSharedPtrMessage* msg, SrsFormat* format
...
+                }
+            } else if (format->vcodec->id == SrsVideoCodecIdHEVC) {
+                if ((err = SrsVideoFrame::parse_hevc_b_frame(sample, format, is_b_frame)) != srs_success) {
+                    return srs_error_wrap(err, "parse bframe");
```
Comment (xiaozhihong) [inline trunk/src/app/srs_app_rtc_source.cpp:1185]: is "parse hevc bframe " better?

File: trunk/src/app/srs_app_rtc_conn.cpp (hunk 20 above)
Comment (duiniuluantanqin) [reply trunk/src/app/srs_app_rtc_conn.cpp:3136]: Compatibility

File: trunk/src/app/srs_app_stream_bridge.cpp (hunk 21 above)
Comment (duiniuluantanqin) [reply trunk/src/app/srs_app_stream_bridge.cpp:161]: Since the default parameter for initialization (init_for_play_before_publishing) is set to H.264, it becomes necessary to update the codec format when the source uses H.265; otherwise, the codec retrieved during SDP negotiation will invariably remain H.264. Moreover, updates are required exclusively in scenarios involving codecs other than H.264.

File: trunk/src/app/srs_app_rtc_source.cpp (hunk 22 above)
Comment (duiniuluantanqin) [reply trunk/src/app/srs_app_rtc_source.cpp:1181]: Of course, that's possible.

`TRANS_BY_GPT4`

Comment (duiniuluantanqin) [reply trunk/src/app/srs_app_rtc_source.cpp:1181]: rename it

File: trunk/src/app/srs_app_rtc_source.cpp (hunk 23 above)
Comment (duiniuluantanqin) [reply trunk/src/app/srs_app_rtc_source.cpp:1185]: rename it.

**Comment by winlinvip** [comment]
See #465

**Review by xiaozhihong — APPROVED** [review]

File: trunk/src/kernel/srs_kernel_rtc_rtp.hpp (hunk 3 above)
Comment (winlinvip) [reply trunk/src/kernel/srs_kernel_rtc_rtp.hpp:262]: I didn't remember, but it's ok to rename to Rtp.

Comment (duiniuluantanqin) [reply trunk/src/kernel/srs_kernel_rtc_rtp.hpp:262]: ok

**Comment by duiniuluantanqin** [comment]
浏览器与流媒体的「高清革命」：H.265 终于突破最后一公里！

## 前言

2025 年 4 月，Chrome 136 迎来重大更新，将 H.265（HEVC）纳入 WebRTC 的支持列表；紧随其后，全球领先的开源流媒体服务器 SRS 强势推出 **RTMP→WebRTC(H.265) 直通模式**。首次实现「低带宽、高并发、零插件、毫秒延迟」四位一体的全链路高清视频传输体验，将彻底改写浏览器端视频播放的技术范式。

## 十年困境：H.265 为何难敌 H.264？

H.265 标准于 2013 年问世，同等画质下能够节省 50% 带宽。可惜，一群大佬手握专利大棒，让浏览器厂商望而却步：内置解码器价格昂贵，法律风险难以承受，结果 Chrome、Firefox 等主流浏览器长期将 H.265 拒之门外，被迫依赖 H.264 作为默认编码标准。

音视频行业由此也面临两难，继续使用 H.264吧，就要忍受高昂的带宽成本以及存储成本，而使用 H.265，就无法直接在浏览器上播放视频。因此，厂商和用户不得不另辟蹊径，花样翻新，想出了各种各样的方案来解决这个难题。

## 百花齐放：那些年我们折腾过的「偏方」

1. ActiveX 插件，最古老的方案，IE 时代的遗产，2020 年后彻底消失在大众面前，很多年轻选手可能没听说过这个玩意。
2. WebAssembly，把 FFmpeg 移植进浏览器，灵活性高，但只能使用 CPU 软解码，性能瓶颈明显，无法支撑安防场景的多路视频播放需求。
3. 服务器转码，通过服务器集群将 H.265 实时转码为 H.264，不仅增加了复杂性，还得多买几张显卡。
4. C/S 架构的客户端，算是最后的保底方案，几乎没什么缺点，唯独难在升级维护成本高，用户嫌麻烦。

除此之外，还有很多奇技淫巧，比如定制浏览器，强行内置 H.265 解码器；再比如安装本地应用，硬解后通过WebSocket传输给浏览器进行渲染；又比如，改造 H.265 协议，将其伪装成 H.264 用来骗过浏览器，等等。前辈们用尽洪荒之力，却各有短板。

## 新时代：Chrome 136 与 SRS 7.0 的黄金联手

2025 年 4 月 29 日，Chrome 136 发布，WebRTC 正式支持 H.265 硬件解码，浏览器直接调用底层硬件解码器，瞬间解放 CPU。同期，SRS 7.0 在开源社区重磅发布，新增 RTMP→WebRTC(H.265) 直通负载类型，不做二次转码，完美兼容现有系统，端到端延迟低至毫秒级别，让视频传输一气呵成。由此，开发者无需改动代码，观众端无需安装插件，即可无缝切换到负载 H.265 的低延迟的 WebRTC 分发模式。

## 快速试用

升级 Chrome 至 136+（Safari 18+），拉取 [SRS](https://github.com/ossrs/srs) 最新代码编译启动
```bash
git clone https://github.com/ossrs/srs
cd srs/trunk && ./configure && make 
./objs/srs -c conf/rtmp2rtc.conf
```

通过 Ffmpeg 推送 H.265 视频流
```bash
ffmpeg -stream_loop -1 -re -i input.mp4 -c:v libx265 -preset fast -b:v 2000k -maxrate 2000k -bufsize 4000k -bf 0 -c:a aac -b:a 128k -ar 44100 -ac 2 -f flv rtmp://localhost/live/livestream
```

浏览器打开 `http://localhost:8080/players/whep.html` 并播放
```bash
http://localhost:1985/rtc/v1/whep/?app=live&stream=livestream
```

## 未来展望

Chrome 与 SRS 的「联手」，让 H.265 终于突破浏览器壁垒，用更低成本、更高效率实现高清视频传输。无论你是开发者、企业用户还是普通观众，现在只需简单配置，即可享受「高清不卡顿、省钱又省心」的新一代流媒体体验。

## 参考
1. [Chrome 136 更新详情](https://developer.chrome.com/release-notes/136?hl=zh-cn#h265_hevc_codec_support_in_webrtc)
2. [SRS 官方文档](https://ossrs.net/lts/zh-cn/docs/v7/doc/webrtc)

File: trunk/src/app/srs_app_stream_bridge.cpp (hunk 21 above)
Comment (winlinvip) [reply trunk/src/app/srs_app_stream_bridge.cpp:161]: Should add a comment for this context, see https://github.com/ossrs/srs/pull/4412
