### PR TITLE
Asan: Support parse asan symbol backtrace log. v5.0.113

### LINKED ISSUE #3297: Asan: Parse symbol from address.
When asan error with log, there are some addresses in log (see #3241):

```
==14647== ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60040001a919 at pc 0x6795e2 bp 0x7fdacfc34cf0 sp 0x7fdacfc34ce0
READ of size 1 at 0x60040001a919 thread T1 (srs-hybrid-2)
    #0 0x6795e1 (/usr/local/srs/trunk/objs/srs+0x6795e1)
    #1 0x67e275 (/usr/local/srs/trunk/objs/srs+0x67e275)
    #2 0x67de8a (/usr/local/srs/trunk/objs/srs+0x67de8a)
    #3 0x67d49e (/usr/local/srs/trunk/objs/srs+0x67d49e)
    #4 0x67b21c (/usr/local/srs/trunk/objs/srs+0x67b21c)
    #5 0x67a665 (/usr/local/srs/trunk/objs/srs+0x67a665)
    #6 0x7b3175 (/usr/local/srs/trunk/objs/srs+0x7b3175)
    #7 0x81faf6 (/usr/local/srs/trunk/objs/srs+0x81faf6)
    #8 0x82f7a2 (/usr/local/srs/trunk/objs/srs+0x82f7a2)
    #9 0x82eda2 (/usr/local/srs/trunk/objs/srs+0x82eda2)
    #10 0x810dc4 (/usr/local/srs/trunk/objs/srs+0x810dc4)
    #11 0x810a23 (/usr/local/srs/trunk/objs/srs+0x810a23)
    #12 0x95693c (/usr/local/srs/trunk/objs/srs+0x95693c)
    #13 0x954e4b (/usr/local/srs/trunk/objs/srs+0x954e4b)
    #14 0x9549a8 (/usr/local/srs/trunk/objs/srs+0x9549a8)
    #15 0x863955 (/usr/local/srs/trunk/objs/srs+0x863955)
    #16 0x863a0f (/usr/local/srs/trunk/objs/srs+0x863a0f)
    #17 0xa80868 (/usr/local/srs/trunk/objs/srs+0xa80868)
    #18 0xa81157 (/usr/local/srs/trunk/objs/srs+0xa81157)
    #19 0x8f6181 (/usr/local/srs/trunk/objs/srs+0x8f6181)
    #20 0x8f4aa3 (/usr/local/srs/trunk/objs/srs+0x8f4aa3)
    #21 0x60040000a0af (+0xa0af)
```

Which can be parsed to symbols, similar to:

```cpp
void SrsCplxError::srs_assert(bool expression)
{
#if defined(SRS_BACKTRACE) && defined(__linux)
    if (!expression) {
        void* addresses[64];
        int nn_addresses = backtrace(addresses, sizeof(addresses) / sizeof(void*));
        char** symbols = backtrace_symbols(addresses, nn_addresses);
```

For example:

```
addresses[0] = 0x6795e1
addresses[1] = 0x67e275
......
```

We can parse the addresses from log of asan, then parse to symbols, then we don't need the binary to reply the issue.

### PR DESCRIPTION
**Pull request by chen-guanghua**
asan: support parse asan symbol backtrace log

### CODE REVIEW

File: trunk/src/main/srs_main_server.cpp [hunk 1]
```diff
@@ -84,7 +85,20 @@ extern void srs_free_global_system_ips();
...
 {
-    srs_trace("%s", str);
+    char buffer[256];
+
+    std::vector<std::string> asan_logs = srs_string_split(string(str), "\n");
+    size_t log_count = asan_logs.size();
+    for (size_t i = 0; i < log_count; i++) {
+        std::string l = srs_string_trim_start(asan_logs[i], " ");
+
+        if (srs_string_starts_with(l, "#")) {
```
Comment (winlinvip) [inline trunk/src/main/srs_main_server.cpp]: If asan already has the symbol table, there is no need for parsing, for example [3300](https://github.com/ossrs/srs/issues/3300#issuecomment-1347574311):

```
==6821==ERROR: AddressSanitizer: memcpy-param-overlap: memory ranges [0x631000190800,0x631000190814) and [0x63100019080c, 0x631000190820) overlap
    #0 0x7f4cb027dffe  (/lib64/libasan.so.5+0x99ffe)
    #1 0x65e714 in SrsBuffer::read_bytes(char*, int) src/kernel/srs_kernel_buffer.cpp:238
    #2 0xc03c14 in SrsLazyGbMediaTcpConn::do_cycle() src/app/srs_app_gb28181.cpp:1448
    #3 0xc020d0 in SrsLazyGbMediaTcpConn::cycle() src/app/srs_app_gb28181.cpp:1316
    #4 0x8ef256 in SrsFastCoroutine::cycle() src/app/srs_app_st.cpp:285
    #5 0x8ef343 in SrsFastCoroutine::pfn(void*) src/app/srs_app_st.cpp:300
    #6 0xc21b69 in _st_thread_main /home/tmp/srs/trunk/objs/Platform-Linux-3.10.0-GCC9.3.1-SRS5-x86_64/st-srs/sched.c:380
    #7 0xc22463 in st_thread_create /home/tmp/srs/trunk/objs/Platform-Linux-3.10.0-GCC9.3.1-SRS5-x86_64/st-srs/sched.c:666
    #8 0x7f4caa919647  (<unknown module>)
```

Only cases like [3297](https://github.com/ossrs/srs/issues/3297#issue-1485670484) require parsing.

```
==14647== ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60040001a919 at pc 0x6795e2 bp 0x7fdacfc34cf0 sp 0x7fdacfc34ce0
READ of size 1 at 0x60040001a919 thread T1 (srs-hybrid-2)
    #0 0x6795e1 (/usr/local/srs/trunk/objs/srs+0x6795e1)
    #1 0x67e275 (/usr/local/srs/trunk/objs/srs+0x67e275)
    #2 0x67de8a (/usr/local/srs/trunk/objs/srs+0x67de8a)
    #3 0x67d49e (/usr/local/srs/trunk/objs/srs+0x67d49e)
```

`TRANS_BY_GPT3`

File: trunk/src/main/srs_main_server.cpp [hunk 2]
```diff
@@ -84,7 +85,21 @@ extern void srs_free_global_system_ips();
...
-    srs_trace("%s", str);
+    char buf[256];
+
+    std::vector<std::string> asan_logs = srs_string_split(string(str), "\n");
+    size_t log_count = asan_logs.size();
+    for (size_t i = 0; i < log_count; i++) {
+        std::string l = srs_string_trim_start(asan_logs[i], " ");
+
+        if (srs_string_starts_with(l, "#")) {
+            if ((srs_parse_asan_backtrace_symbols((char*)l.c_str(), buf)) == ERROR_SUCCESS) {
```
Comment (winlinvip) [inline trunk/src/main/srs_main_server.cpp]: Since we have already used an int return value, we might as well make use of it.

```cpp
for (size_t i = 0; i < log_count; i++) {
  std::string log = srs_string_trim_start(asan_logs[i], " ");
  if (!srs_string_starts_with(log, "#")) {
    srs_trace("%s", log.c_str());
    continue;
  }

  int r0 = srs_parse_asan_backtrace_symbols((char*)log.c_str(), buf);
  if (r0 != ERROR_SUCCESS) {
    srs_trace("%s, r0=%d", log.c_str(), r0);
  } else {
    srs_trace("%s, %s", log.c_str(), buf);
  }
```

`TRANS_BY_GPT3`
