### PR TITLE
RTC: fix rtc publisher pli cid

### LINKED ISSUE #3317: WebRTC: Reqeust PLI invalid play cid.
Publish by WebRTC, play by RTMP.

Logs is here: [play.log](https://github.com/ossrs/srs/files/10236559/play.log) [publisher.log](https://github.com/ossrs/srs/files/10236560/publisher.log) [srs.log](https://github.com/ossrs/srs/files/10236561/srs.log)

The play cid in log is `58nn81py`, but there is no client:

```log
grep 15574p9l srs.log |grep PLI
[2022-12-15 19:29:05.557][INFO][99372][58nn81py] RTC: Need PLI ssrc=4183764528, play=[58nn81py], publish=[15574p9l], count=1/1
[2022-12-15 19:29:05.557][INFO][99372][15574p9l] RTC: Request PLI ssrc=4183764528, play=[58nn81py], count=1/1, bytes=12B
```

The log of `58nn81py`:

```bash
grep 58nn81py srs.log
[2022-12-15 19:28:33.699][INFO][99372][58nn81py] RTC: Need PLI ssrc=1298984345, play=[58nn81py], publish=[z220f1a1], count=1/1
[2022-12-15 19:28:33.699][INFO][99372][z220f1a1] RTC: Request PLI ssrc=1298984345, play=[58nn81py], count=1/1, bytes=12B
[2022-12-15 19:28:44.076][WARN][99372][58nn81py][35][LARGE_TIMER] twcc delay 155ms > 100ms, count=1/1
[2022-12-15 19:28:45.781][INFO][99372][58nn81py] RTC: Need PLI ssrc=1298984345, play=[58nn81py], publish=[z220f1a1], count=3/3
[2022-12-15 19:28:45.781][INFO][99372][z220f1a1] RTC: Request PLI ssrc=1298984345, play=[58nn81py], count=3/3, bytes=12B
[2022-12-15 19:28:57.833][INFO][99372][58nn81py] RTC: Need PLI ssrc=1298984345, play=[58nn81py], publish=[z220f1a1], count=5/5
[2022-12-15 19:28:57.833][INFO][99372][z220f1a1] RTC: Request PLI ssrc=1298984345, play=[58nn81py], count=5/5, bytes=12B
[2022-12-15 19:29:05.557][INFO][99372][58nn81py] RTC: Need PLI ssrc=4183764528, play=[58nn81py], publish=[15574p9l], count=1/1
[2022-12-15 19:29:05.557][INFO][99372][15574p9l] RTC: Request PLI ssrc=4183764528, play=[58nn81py], count=1/1, bytes=12B
[2022-12-15 19:29:17.596][INFO][99372][58nn81py] RTC: Need PLI ssrc=4183764528, play=[58nn81py], publish=[15574p9l], count=3/3
[2022-12-15 19:29:17.596][INFO][99372][15574p9l] RTC: Request PLI ssrc=4183764528, play=[58nn81py], count=3/3, bytes=12B
[2022-12-15 19:29:21.727][WARN][99372][58nn81py][35][LARGE_TIMER] twcc delay 130ms > 100ms, count=1/1
[2022-12-15 19:29:29.685][INFO][99372][58nn81py] RTC: Need PLI ssrc=4183764528, play=[58nn81py], publish=[15574p9l], count=5/5
[2022-12-15 19:29:29.685][INFO][99372][15574p9l] RTC: Request PLI ssrc=4183764528, play=[58nn81py], count=5/5, bytes=12B
[2022-12-15 19:29:41.746][INFO][99372][58nn81py] RTC: Need PLI ssrc=4183764528, play=[58nn81py], publish=[15574p9l], count=7/7
[2022-12-15 19:29:41.746][INFO][99372][15574p9l] RTC: Request PLI ssrc=4183764528, play=[58nn81py], count=7/7, bytes=12B
[2022-12-15 19:29:53.804][INFO][99372][58nn81py] RTC: Need PLI ssrc=4183764528, play=[58nn81py], publish=[15574p9l], count=9/9
[2022-12-15 19:29:53.804][INFO][99372][15574p9l] RTC: Request PLI ssrc=4183764528, play=[58nn81py], count=9/9, bytes=12B
[2022-12-15 19:30:05.876][INFO][99372][58nn81py] RTC: Need PLI ssrc=4183764528, play=[58nn81py], publish=[15574p9l], count=11/11
[2022-12-15 19:30:05.876][INFO][99372][15574p9l] RTC: Request PLI ssrc=4183764528, play=[58nn81py], count=11/11, bytes=12B
[2022-12-15 19:30:17.931][INFO][99372][58nn81py] RTC: Need PLI ssrc=4183764528, play=[58nn81py], publish=[15574p9l], count=13/13
[2022-12-15 19:30:17.931][INFO][99372][15574p9l] RTC: Request PLI ssrc=4183764528, play=[58nn81py], count=13/13, bytes=12B
[2022-12-15 19:30:29.977][INFO][99372][58nn81py] RTC: Need PLI ssrc=4183764528, play=[58nn81py], publish=[15574p9l], count=15/15
[2022-12-15 19:30:29.977][INFO][99372][15574p9l] RTC: Request PLI ssrc=4183764528, play=[58nn81py], count=15/15, bytes=12B
[2022-12-15 19:30:33.317][WARN][99372][58nn81py][35][LARGE_TIMER] twcc delay 156ms > 100ms, count=3/3
[2022-12-15 19:30:42.055][INFO][99372][58nn81py] RTC: Need PLI ssrc=4183764528, play=[58nn81py], publish=[15574p9l], count=17/17
[2022-12-15 19:30:42.055][INFO][99372][15574p9l] RTC: Request PLI ssrc=4183764528, play=[58nn81py], count=17/17, bytes=12B
```

### PR DESCRIPTION
**Pull request by xiaozhihong**
RTC publisher cycle request PLI, use correct context id.

### CODE REVIEW

File: trunk/src/app/srs_app_rtc_conn.cpp [hunk 1]
```diff
@@ -1613,13 +1613,12 @@ srs_error_t SrsRtcPublishStream::on_rtcp_xr(SrsRtcpXr* rtcp)
 
 void SrsRtcPublishStream::request_keyframe(uint32_t ssrc)
 {
-    SrsContextId sub_cid = _srs_context->get_id();
-    pli_worker_->request_keyframe(ssrc, sub_cid);
+    pli_worker_->request_keyframe(ssrc, cid_);
```
Comment (winlinvip) [inline trunk/src/app/srs_app_rtc_conn.cpp]: After you made this change, the PLI triggered by RTC play is incorrect.

The mistake here is with the sub_cid. When converting RTC to RTMP, this ID is incorrect.

cid_' is the ID of the self-push stream. `_srs_context->get_id()` is the ID of the current coroutine.

`TRANS_BY_GPT3`

File: trunk/src/app/srs_app_rtc_conn.cpp [hunk 2]
```diff
@@ -1611,15 +1611,14 @@ srs_error_t SrsRtcPublishStream::on_rtcp_xr(SrsRtcpXr* rtcp)
     return err;
 }
 
-void SrsRtcPublishStream::request_keyframe(uint32_t ssrc)
+void SrsRtcPublishStream::request_keyframe(uint32_t ssrc, SrsContextId cid)
```
Comment (chen-guanghua) [inline trunk/src/app/srs_app_rtc_conn.cpp:1614]: Is adding the cid parameter to solve the issue of publisher's periodic retrieval?

`TRANS_BY_GPT3`

**Review by winlinvip — DISMISSED** [review]

**Review by winlinvip — APPROVED** [review]

**Review by chen-guanghua — APPROVED** [review]

File: trunk/src/app/srs_app_rtc_conn.cpp (hunk 2 above)
Comment (xiaozhihong) [reply trunk/src/app/srs_app_rtc_conn.cpp:1614]: Yes, it is passed from the outside, and the producer directly passes its own cid.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Check by WebRTC publish and play:

```
grep 'Need PLI' t.log
[2023-01-18 09:28:06.769][INFO][22999][i3oz708r] RTC: Need PLI ssrc=2778412766, play=[i3oz708r], publish=[978q64hp], count=1/1

grep i3oz708r t.log |more
[2023-01-18 09:28:06.757][INFO][22999][i3oz708r] HTTP #0 127.0.0.1:54772 POST http://localhost:1985/rtc/v1/play/, content-length=6945
[2023-01-18 09:28:06.757][INFO][22999][i3oz708r] RTC play webrtc://localhost/live/livestream, api=http://localhost:1985/rtc/v1/play/, tid=8720ddb, clientip=127.0.0.1, app=live, stream=livestream, offer=6387B, eip=, codec=, srtp=, dtls=
[2023-01-18 09:28:06.758][INFO][22999][i3oz708r] ignore attribute=, value=
[2023-01-18 09:28:06.760][INFO][22999][i3oz708r] RTC player nack=1, nnc=1
[2023-01-18 09:28:06.760][INFO][22999][i3oz708r] RTC connection player gcc=3
[2023-01-18 09:28:06.760][INFO][22999][i3oz708r] RTC: Init tracks {track: 03bd982c-a376-426b-bbc8-f21c394028bf, is_active: 0=>1},{track: 0ca3a4fb-c0c1-4efa-b1eb-d3b50ab83066, is_active: 0=>1}, ok
[2023-01-18 09:28:06.760][INFO][22999][i3oz708r] Best matched ip=172.20.10.3, ifname=en6
[2023-01-18 09:28:06.760][INFO][22999][i3oz708r] RTC: Use candidates 172.20.10.3, protocol=udp
[2023-01-18 09:28:06.761][INFO][22999][i3oz708r] RTC init session, user=1428ym3r:CAyM, url=/live/livestream, encrypt=1/1, DTLS(role=passive, version=auto), timeout=30000ms, nack=1

grep 978q64hp t.log |more
[2023-01-18 09:28:02.684][INFO][22999][978q64hp] HTTP #0 127.0.0.1:54744 POST http://localhost:1985/rtc/v1/publish/, content-length=6039
[2023-01-18 09:28:02.685][INFO][22999][978q64hp] RTC publish webrtc://localhost/live/livestream, api=http://localhost:1985/rtc/v1/publish/, tid=3cd128e, clientip=127.0.0.1, app=live, stream=livestream, offer=5558B, eip=, codec=
[2023-01-18 09:28:02.685][INFO][22999][978q64hp] ignore attribute=, value=
[2023-01-18 09:28:02.687][INFO][22999][978q64hp] RTC publisher nack=1, nnc=1, pt-drop=0, twcc=1/3
[2023-01-18 09:28:02.688][INFO][22999][978q64hp] RTC: Init tracks {track: 03bd982c-a376-426b-bbc8-f21c394028bf, is_active: 0=>1},{track: 0ca3a4fb-c0c1-4efa-b1eb-d3b50ab83066, is_active: 0=>1}, ok
[2023-01-18 09:28:02.688][INFO][22999][978q64hp] Best matched ip=172.20.10.3, ifname=en6
[2023-01-18 09:28:02.688][INFO][22999][978q64hp] RTC: Use candidates 172.20.10.3, protocol=udp
[2023-01-18 09:28:02.689][INFO][22999][978q64hp] RTC init session, user=06tt9fw6:qJXA, url=/live/livestream, encrypt=1/1, DTLS(role=passive, version=auto), timeout=30000ms, nack=1
```

**Comment by winlinvip** [comment]
Check by
1. Publish by RTMP.
2. Play by WebRTC.
3. Publish by WebRTC.
4. Play by WebRTC.

```
grep 'Need PLI' t.log
[2023-01-18 09:31:33.018][INFO][22999][4573858y] RTC: Need PLI ssrc=694299555, play=[3192x165], publish=[3192x165], count=1/1

grep 3192x165 t.log |more
[2023-01-18 09:31:29.275][INFO][22999][3192x165] HTTP #0 127.0.0.1:55978 POST http://localhost:1985/rtc/v1/publish/, content-length=6031
[2023-01-18 09:31:29.276][INFO][22999][3192x165] RTC publish webrtc://localhost/live/livestream, api=http://localhost:1985/rtc/v1/publish/, tid=5e44f86, clientip=127.0.0.1, app=live, stream=livestream, offer=5550B, eip=, codec=
[2023-01-18 09:31:29.276][INFO][22999][3192x165] ignore attribute=, value=
[2023-01-18 09:31:29.278][INFO][22999][3192x165] RTC publisher nack=1, nnc=1, pt-drop=0, twcc=1/3
[2023-01-18 09:31:29.279][INFO][22999][3192x165] RTC: Init tracks {track: f450bb34-1711-44e9-9f8f-9287551de27d, is_active: 0=>1},{track: 90e9f082-a5d1-4d97-9676-bc73abfeeca6, is_active: 0=>1}, ok
[2023-01-18 09:31:29.279][INFO][22999][3192x165] Best matched ip=172.20.10.3, ifname=en6
[2023-01-18 09:31:29.279][INFO][22999][3192x165] RTC: Use candidates 172.20.10.3, protocol=udp
[2023-01-18 09:31:29.280][INFO][22999][3192x165] RTC init session, user=49n59fvh:/RNT, url=/live/livestream, encrypt=1/1, DTLS(role=passive, version=auto), timeout=30000ms, nack=1
```

After RTC2RTMP, the bridge initiates a PLI request, causing both play and publish to be the same.

This confusion is too significant. Can we use the bridge's CID for play? Also, the bridge for RTC2RTMP does not have any logs. It would be helpful to add a log to identify the context of this issue.

`TRANS_BY_GPT3`

File: trunk/src/app/srs_app_rtc_source.cpp [hunk 3]
```diff
@@ -703,7 +703,8 @@ srs_error_t SrsRtcSource::on_timer(srs_utime_t interval)
 
     for (int i = 0; i < (int)stream_desc_->video_track_descs_.size(); i++) {
         SrsRtcTrackDescription* desc = stream_desc_->video_track_descs_.at(i);
-        publish_stream_->request_keyframe(desc->ssrc_);
+        srs_trace("RTC: to rtmp bridge request key frame, ssrc=%u, publisher cid=%s", desc->ssrc_, publish_stream_->context_id().c_str());
```
Comment (xiaozhihong) [inline trunk/src/app/srs_app_rtc_source.cpp:706]: rtc to rtmp bridge requests keyframes triggered in the timer coroutine, multiple rtc publishers are one cid.

Add a log line to clearly indicate that it is a PLI request from RTC to RTMP.

`TRANS_BY_GPT3`

Comment (xiaozhihong) [reply trunk/src/app/srs_app_rtc_source.cpp:706]:
```
[2023-01-18 10:18:25.082][INFO][66963][004u456w] RTC: to rtmp bridge request key frame, ssrc=853223138, publisher cid=x500t79c
[2023-01-18 10:18:25.082][INFO][66963][004u456w] RTC: Need PLI ssrc=853223138, play=[x500t79c], publish=[x500t79c], count=1/1
[2023-01-18 10:18:25.082][INFO][66963][x500t79c] RTC: Request PLI ssrc=853223138, play=[x500t79c], count=1/1, bytes=12B
```

**Review by winlinvip — APPROVED** [review]
